import type { TableSpec } from "./coherent-cut.js";

// Explicit PRAGMA-derived columns and deterministic primary-key ordering.
export const DURABLE_CORE_TABLE_SPECS_A: readonly TableSpec[] = [
  { manifest: "purge", table: "purge_ledger", order_by: "ledger_revision", columns: {
      "ledger_revision": "int",
      "erasure_id": "text",
      "non_revealing_subject_digest": "text",
      "disposition": "text",
      "receipt_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_event", order_by: "investigation_id, sequence", columns: {
      "investigation_id": "text",
      "sequence": "int",
      "event_id": "text",
      "kind": "text",
      "payload_handle_ref": "text",
      "payload_digest": "text",
      "actor_ref": "text",
      "verifier_ref": "text-or-null",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_command", order_by: "command_id", columns: {
      "command_id": "text",
      "op_kind": "text",
      "expected_old_revision": "int",
      "expected_new_revision": "int",
      "expected_old_event_head": "int",
      "expected_new_event_head": "int",
      "expected_epoch": "int",
      "principal_ref": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "deployment_generation": "text",
      "global_purge_revision": "int",
      "scope_purge_revision": "int-or-null",
      "observed_at": "text",
      "expires_at": "text",
      "oh_investigation_id": "text-or-null",
      "oh_revision": "int-or-null",
      "oh_protocol_version": "text-or-null",
      "oh_goal": "text-or-null",
      "oh_scope_snapshot_id": "text-or-null",
      "oh_scope_snapshot_revision": "int-or-null",
      "oh_evidence_grade": "text-or-null",
      "oh_lane": "text-or-null",
      "oh_lane_registrations_json": "text-or-null",
      "oh_obligations_json": "text-or-null",
      "oh_hypotheses_json": "text-or-null",
      "oh_portfolio_ref": "text-or-null",
      "oh_debt_refs_json": "text-or-null",
      "oh_checkpoint_head": "int-or-null",
      "oh_principal_ref": "text-or-null",
      "oh_input_digest": "text-or-null",
      "oh_policy_generation": "text-or-null",
      "oh_policy_authority_ref": "text-or-null",
      "oh_deployment_generation": "text-or-null",
      "oh_idempotency_key": "text-or-null",
      "oh_model_profile_ref": "text-or-null",
      "oh_observed_execution": "text-or-null",
      "oh_observed_fidelity": "text-or-null",
      "oh_observed_assurance": "text-or-null",
      "oh_status": "text-or-null",
      "oh_supersedes_id": "text-or-null",
      "oh_supersession_reason": "text-or-null",
      "oh_event_head": "int-or-null",
      "oh_created_at": "text-or-null",
      "oh_updated_at": "text-or-null",
      "oe_investigation_id": "text-or-null",
      "oe_sequence": "int-or-null",
      "oe_event_id": "text-or-null",
      "oe_kind": "text-or-null",
      "oe_payload_handle_ref": "text-or-null",
      "oe_payload_digest": "text-or-null",
      "oe_actor_ref": "text-or-null",
      "oe_verifier_ref": "text-or-null",
      "oe_created_at": "text-or-null",
      "nh_investigation_id": "text",
      "nh_revision": "int",
      "nh_protocol_version": "text",
      "nh_goal": "text",
      "nh_scope_snapshot_id": "text",
      "nh_scope_snapshot_revision": "int",
      "nh_evidence_grade": "text",
      "nh_lane": "text",
      "nh_lane_registrations_json": "text",
      "nh_obligations_json": "text",
      "nh_hypotheses_json": "text",
      "nh_portfolio_ref": "text",
      "nh_debt_refs_json": "text",
      "nh_checkpoint_head": "int",
      "nh_principal_ref": "text",
      "nh_input_digest": "text",
      "nh_policy_generation": "text",
      "nh_policy_authority_ref": "text",
      "nh_deployment_generation": "text",
      "nh_idempotency_key": "text",
      "nh_model_profile_ref": "text",
      "nh_observed_execution": "text-or-null",
      "nh_observed_fidelity": "text-or-null",
      "nh_observed_assurance": "text-or-null",
      "nh_status": "text",
      "nh_supersedes_id": "text-or-null",
      "nh_supersession_reason": "text-or-null",
      "nh_event_head": "int",
      "nh_created_at": "text",
      "nh_updated_at": "text",
      "ne_investigation_id": "text",
      "ne_sequence": "int",
      "ne_event_id": "text",
      "ne_kind": "text",
      "ne_payload_handle_ref": "text",
      "ne_payload_digest": "text",
      "ne_actor_ref": "text",
      "ne_verifier_ref": "text-or-null",
      "ne_created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_head", order_by: "investigation_id", columns: {
      "investigation_id": "text",
      "revision": "int",
      "protocol_version": "text",
      "goal": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "evidence_grade": "text",
      "lane": "text",
      "lane_registrations_json": "text",
      "obligations_json": "text",
      "hypotheses_json": "text",
      "portfolio_ref": "text",
      "debt_refs_json": "text",
      "checkpoint_head": "int",
      "principal_ref": "text",
      "input_digest": "text",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "deployment_generation": "text",
      "idempotency_key": "text",
      "model_profile_ref": "text",
      "observed_execution": "text-or-null",
      "observed_fidelity": "text-or-null",
      "observed_assurance": "text-or-null",
      "status": "text",
      "supersedes_id": "text-or-null",
      "supersession_reason": "text-or-null",
      "event_head": "int",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_epoch", order_by: "singleton", columns: {
      "singleton": "int",
      "generation": "int"
  }, required: false },
  { manifest: "heads", table: "research_workflow_run", order_by: "operation_id", columns: {
      "operation_id": "text",
      "investigation_id": "text",
      "initial_revision": "int",
      "current_revision": "int",
      "principal_ref": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "authorization_receipt_ref": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "purge_revision": "int",
      "idempotency_key": "text",
      "handler_generation": "text",
      "initial_manifest_json": "text",
      "next_stage_index": "int",
      "state": "text",
      "configuration_ref": "text-or-null",
      "configuration_required": "int",
      "cancellation_receipt_ref": "text-or-null",
      "created_at": "text",
      "first_failure_json": "text-or-null",
      "latest_failure_json": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_workflow_attempt", order_by: "operation_id, stage_index", columns: {
      "operation_id": "text",
      "stage_index": "int",
      "request_json": "text",
      "request_sha256": "text",
      "attempt_ref": "text",
      "expected_revision": "int",
      "budget_receipt_ref": "text",
      "budget_expires_at_ms": "int",
      "state": "text",
      "output_json": "text-or-null",
      "created_at": "text",
      "first_failure_json": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_workflow_checkpoint", order_by: "operation_id, stage_index", columns: {
      "operation_id": "text",
      "stage_index": "int",
      "request_sha256": "text",
      "receipt_json": "text",
      "receipt_sha256": "text",
      "ledger_event_id": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_workflow_citation_binding", order_by: "operation_id, stage_index", columns: {
      "operation_id": "text",
      "stage_index": "int",
      "attempt_ref": "text",
      "request_sha256": "text",
      "receipt_id": "text",
      "receipt_revision": "int",
      "receipt_sha256": "text",
      "bound_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_query_result", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "state": "text",
      "result_json": "text-or-null",
      "result_digest": "text-or-null",
      "trace_id": "text-or-null",
      "trace_revision": "int-or-null",
      "coverage_claim": "text",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_query_trace", order_by: "trace_id, revision", columns: {
      "trace_id": "text",
      "revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "trace_json": "text",
      "trace_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_exhaustive_job", order_by: "job_id", columns: {
      "job_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "scope_digest": "text",
      "plan_id": "text",
      "coverage_denominator_ref": "text",
      "denominator_shard_ids_json": "text",
      "state": "text",
      "denominator_shards": "int",
      "settled_shards": "int-or-null",
      "total_scanned_sections": "int-or-null",
      "total_matches": "int-or-null",
      "result_artifact_ref": "text-or-null",
      "coverage_receipt_ref": "text-or-null",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_exhaustive_shard", order_by: "job_id, shard_id", columns: {
      "job_id": "text",
      "shard_id": "text",
      "outcome_json": "text",
      "outcome_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_exhaustive_workflow", order_by: "workflow_id", columns: {
      "workflow_id": "text",
      "job_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "request_identity_digest": "text",
      "state": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "raw_file_capture", order_by: "capture_id", columns: {
      "capture_id": "text",
      "principal_ref": "text",
      "owner_system_id": "text",
      "source_namespace_id": "text",
      "source_revision_ref": "text",
      "source_logical_id": "text",
      "source_owner_generation": "text",
      "idempotency_key": "text",
      "original_file_name": "text",
      "request_digest": "text",
      "residency_key_json": "text",
      "residency_key_digest": "text",
      "content_sha256": "text",
      "size_bytes": "int",
      "content_type": "text",
      "state": "text",
      "object_key": "text",
      "receipt_json": "text-or-null",
      "receipt_sha256": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "expires_at": "text",
      "target_source_id": "text-or-null",
      "expected_head_revision_ref": "text-or-null"
  }, required: false },
  { manifest: "sources", table: "raw_markdown_conversion", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "capture_id": "text",
      "content_sha256": "text",
      "size_bytes": "int",
      "request_sha256": "text",
      "request_json": "text",
      "authority_sha256": "text",
      "attempt_id": "text",
      "state": "text",
      "result_json": "text-or-null",
      "result_sha256": "text-or-null",
      "output_object_key": "text",
      "receipt_object_key": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "sources", table: "raw_normalized_admission", order_by: "admission_operation_id", columns: {
      "admission_operation_id": "text",
      "principal_ref": "text",
      "capture_id": "text",
      "conversion_operation_id": "text",
      "idempotency_key": "text",
      "input_fingerprint": "text",
      "candidate_ref": "text",
      "source_revision_ref": "text",
      "source_view_ref": "text",
      "snapshot_view_json": "text",
      "snapshot_view_sha256": "text",
      "policy_snapshot_json": "text",
      "policy_snapshot_sha256": "text",
      "policy_revision": "int",
      "ingest_operation_id": "text-or-null",
      "state": "text",
      "reason_codes_json": "text",
      "receipt_json": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "sources", table: "workspace_mcp_observation", order_by: "observation_id", columns: {
      "observation_id": "text",
      "plan_id": "text",
      "principal_ref": "text",
      "deployment_generation": "text",
      "auth_profile": "text",
      "google_transport": "text",
      "idempotency_key": "text",
      "receipt_sha256": "text",
      "receipt_json": "text",
      "observation_json": "text",
      "observation_sha256": "text",
      "disposition": "text",
      "reason_codes_json": "text",
      "observed_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "workspace_mcp_raw_normalized_admission", order_by: "binding_id", columns: {
      "binding_id": "text",
      "principal_ref": "text",
      "deployment_generation": "text",
      "auth_profile": "text",
      "google_transport": "text",
      "idempotency_key": "text",
      "plan_idempotency_key": "text",
      "plan_id": "text",
      "plan_sha256": "text",
      "observation_id": "text",
      "observation_receipt_sha256": "text",
      "capture_id": "text",
      "capture_content_sha256": "text",
      "conversion_operation_id": "text",
      "admission_operation_id": "text-or-null",
      "state": "text",
      "created_at": "text",
      "updated_at": "text",
      "observation_principal_ref": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_reservation", order_by: "intent_id, intent_revision", columns: {
      "intent_id": "text",
      "intent_revision": "int",
      "artifact_id": "text",
      "artifact_revision": "int",
      "request_sha256": "text",
      "spec_digest": "text",
      "manifest_r2_key": "text",
      "expected_head_revision": "int-or-null",
      "spec_ref_id": "text",
      "spec_ref_revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "intent_json": "text",
      "principal_ref": "text",
      "idempotency_key": "text",
      "payload_ref": "text",
      "topic": "text",
      "planned_objects_json": "text",
      "state": "text",
      "created_at": "text",
      "updated_at": "text",
      "cow_operation_id": "text-or-null",
      "cow_attempt_ref": "text-or-null",
      "cow_request_sha256": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_head", order_by: "artifact_id", columns: {
      "artifact_id": "text",
      "head_revision": "int",
      "manifest_r2_key": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_binding", order_by: "artifact_id, revision", columns: {
      "artifact_id": "text",
      "revision": "int",
      "intent_id": "text",
      "intent_revision": "int",
      "expected_head_revision": "int-or-null",
      "principal_ref": "text",
      "spec_ref_id": "text",
      "spec_ref_revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "manifest_r2_key": "text",
      "manifest_sha256": "text",
      "manifest_size_bytes": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_object", order_by: "artifact_id, revision, object_kind, object_ref", columns: {
      "artifact_id": "text",
      "revision": "int",
      "object_kind": "text",
      "object_ref": "text",
      "section_ordinal": "int-or-null",
      "receipt_json": "text",
      "residency_key_json": "text",
      "residency_key_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_model_attempt", order_by: "attempt_id", columns: {
      "attempt_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "reservation_id": "text",
      "attempt_number": "int",
      "principal_ref": "text",
      "operation_kind": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "request_json": "text",
      "authority_json": "text",
      "route_ref": "text",
      "prompt_generation": "text",
      "schema_generation": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "state": "text",
      "receipt_json": "text-or-null",
      "receipt_sha256": "text-or-null",
      "output_object_ref": "text-or-null",
      "output_sha256": "text-or-null",
      "output_size_bytes": "int-or-null",
      "readback_sha256": "text-or-null",
      "error_code": "text-or-null",
      "reason_codes_json": "text",
      "started_at": "text",
      "ended_at": "text-or-null",
      "workflow_binding_kind": "text",
      "cow_operation_id": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_reference_manifest", order_by: "manifest_id, manifest_revision", columns: {
      "manifest_id": "text",
      "manifest_revision": "int",
      "manifest_digest": "text",
      "r2_content_sha256": "text",
      "r2_residency_key_json": "text",
      "r2_residency_key_digest": "text",
      "r2_key": "text",
      "r2_etag": "text",
      "r2_size_bytes": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "scope_snapshot_digest": "text",
      "policy_authority_ref": "text",
      "authorization_receipt_ref": "text",
      "principal_ref": "text",
      "credential_generation": "text",
      "pack_ref_id": "text",
      "pack_ref_revision": "int",
      "trace_ref_id": "text",
      "trace_ref_revision": "int",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "state": "text",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
];
