import type { TableSpec } from "./coherent-cut.js";

// Explicit PRAGMA-derived columns and deterministic primary-key ordering.
export const DURABLE_CORE_TABLE_SPECS_B: readonly TableSpec[] = [
  { manifest: "heads", table: "research_model_fingerprint", order_by: "observation_seq", columns: {
      "observation_seq": "int",
      "fingerprint_ref": "text",
      "route_ref": "text",
      "fingerprint_sha256": "text",
      "fingerprint_json": "text",
      "observed_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_model_output", order_by: "output_object_ref", columns: {
      "output_object_ref": "text",
      "attempt_id": "text",
      "principal_ref": "text",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "request_sha256": "text",
      "workflow_budget_receipt_ref": "text",
      "residency_domain_json": "text",
      "residency_domain_sha256": "text",
      "r2_key": "text-or-null",
      "r2_etag": "text-or-null",
      "output_sha256": "text-or-null",
      "output_size_bytes": "int-or-null",
      "readback_sha256": "text-or-null",
      "state": "text",
      "created_at": "text",
      "committed_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_model_pricing_snapshot", order_by: "pricing_snapshot_ref", columns: {
      "pricing_snapshot_ref": "text",
      "route_ref": "text",
      "route_version": "text",
      "provider": "text",
      "exact_model_id": "text",
      "pricing_basis": "text",
      "input_rate_usd_per_1k_tokens": "text",
      "output_rate_usd_per_1k_tokens": "text",
      "provenance_ref": "text",
      "approval_receipt_ref": "text",
      "effective_at": "text",
      "expires_at": "text",
      "snapshot_sha256": "text",
      "snapshot_json": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_candidate", order_by: "candidate_ref", columns: {
      "candidate_ref": "text",
      "route_ref": "text",
      "route_version": "text",
      "candidate_sha256": "text",
      "candidate_json": "text",
      "staged_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_active_generation", order_by: "route_ref", columns: {
      "route_ref": "text",
      "route_version": "text",
      "candidate_ref": "text",
      "candidate_sha256": "text",
      "promotion_ref": "text",
      "promoted_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_qualification_proof", order_by: "qualification_ref", columns: {
      "qualification_ref": "text",
      "proof_sha256": "text",
      "qualification_json": "text",
      "route_ref": "text",
      "route_version": "text",
      "candidate_ref": "text",
      "candidate_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_active_qualification", order_by: "route_ref, route_version", columns: {
      "route_ref": "text",
      "route_version": "text",
      "candidate_ref": "text",
      "candidate_sha256": "text",
      "qualification_ref": "text",
      "qualification_sha256": "text",
      "activated_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_proposal", order_by: "proposal_id, proposal_revision", columns: {
      "proposal_id": "text",
      "proposal_revision": "int",
      "principal_ref": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "page_id": "text",
      "page_revision": "int",
      "page_sha256": "text",
      "page_json": "text",
      "risk_class": "text",
      "body_size": "int",
      "evidence_map_sha256": "text",
      "evidence_map_size": "int",
      "dependency_refs_sha256": "text",
      "state": "text",
      "created_at": "text",
      "published_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_authority", order_by: "proposal_id, proposal_revision", columns: {
      "proposal_id": "text",
      "proposal_revision": "int",
      "evidence_receipt_ref": "text",
      "coverage_receipt_json": "text",
      "dependency_closure_receipt_ref": "text",
      "verifier_receipt_ref": "text",
      "policy_receipt_ref": "text-or-null",
      "coverage_complete": "int",
      "dependency_closure_complete": "int",
      "conflict_count": "int",
      "changes_current_state": "int",
      "state": "text",
      "admitted_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_revision", order_by: "page_id, revision", columns: {
      "page_id": "text",
      "revision": "int",
      "proposal_id": "text",
      "proposal_revision": "int",
      "manifest_ref": "text",
      "page_sha256": "text",
      "page_json": "text",
      "body_object_ref": "text",
      "body_sha256": "text",
      "committer_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_head", order_by: "page_id", columns: {
      "page_id": "text",
      "revision": "int",
      "manifest_ref": "text",
      "outbox_ref": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_outbox", order_by: "outbox_ref", columns: {
      "outbox_ref": "text",
      "page_id": "text",
      "revision": "int",
      "manifest_ref": "text",
      "payload_sha256": "text",
      "state": "text",
      "created_at": "text",
      "delivered_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "wiki_owner_edit_binding", order_by: "proposal_id, proposal_revision", columns: {
      "proposal_id": "text",
      "proposal_revision": "int",
      "principal_ref": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "proposal_page_sha256": "text",
      "base_proposal_id": "text",
      "base_proposal_revision": "int",
      "base_page_id": "text",
      "base_page_revision": "int",
      "base_page_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "ownership", table: "source_namespace_initialization", order_by: "source_namespace_id", columns: {
      "source_namespace_id": "text",
      "principal_ref": "text",
      "credential_generation": "text",
      "profile_id": "text",
      "profile_revision": "int",
      "title": "text",
      "idempotency_key": "text",
      "owner_incarnation_ref": "text",
      "source_owner_generation": "text",
      "ownership_record_revision": "int",
      "source_admission_policy_revision": "int",
      "scope_policy_ref": "text",
      "scope_policy_generation": "int",
      "request_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "raw_ingest_erasure_member", order_by: "source_revision_ref, member_kind, member_id", columns: {
      "source_revision_ref": "text",
      "member_kind": "text",
      "member_id": "text"
  }, required: false },
  { manifest: "generations", table: "model_route_qualification_probe", order_by: "probe_idempotency_key", columns: {
      "probe_idempotency_key": "text",
      "probe_input_sha256": "text",
      "claim_ref": "text",
      "started_at": "text",
      "execution_probe_ref": "text-or-null",
      "observation_sha256": "text-or-null",
      "observation_json": "text-or-null"
  }, required: false },
  { manifest: "generations", table: "model_route_qualification_dispatch", order_by: "probe_idempotency_key", columns: {
      "probe_idempotency_key": "text",
      "probe_input_sha256": "text",
      "claim_ref": "text",
      "state": "text",
      "observation_sha256": "text-or-null",
      "observation_json": "text-or-null",
      "started_at": "text",
      "completed_at": "text-or-null"
  }, required: false },
  { manifest: "projects", table: "project_mutation_guard", order_by: "principal_ref, idempotency_key", columns: {
      "principal_ref": "text",
      "idempotency_key": "text",
      "operation": "text",
      "project_id": "text",
      "expected_revision": "int",
      "next_revision": "int",
      "created_at": "text",
      "project_client_grant_id": "text-or-null",
      "project_client_grant_revision": "int-or-null",
      "client_authority_expires_at": "text-or-null"
  }, required: false },
  { manifest: "projects", table: "project_mutation_receipt", order_by: "principal_ref, idempotency_key", columns: {
      "principal_ref": "text",
      "idempotency_key": "text",
      "operation": "text",
      "project_id": "text",
      "request_sha256": "text",
      "response_json": "text",
      "response_sha256": "text",
      "project_revision": "int",
      "deployment_generation": "text",
      "created_at": "text",
      "project_client_grant_id": "text-or-null",
      "project_client_grant_revision": "int-or-null",
      "client_authority_expires_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_report_admission", order_by: "decision_id", columns: {
      "decision_id": "text",
      "decision_revision": "int",
      "decision": "text",
      "decision_json": "text",
      "decision_sha256": "text",
      "input_json": "text",
      "input_sha256": "text",
      "policy_json": "text",
      "policy_ref": "text",
      "policy_revision": "int",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "policy_expires_at": "text",
      "operation_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "outbox_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "scope_snapshot_digest": "text",
      "authorization_receipt_ref": "text",
      "deployment_generation": "text",
      "source_revision_refs_json": "text",
      "requested_output_class": "text",
      "purpose": "text",
      "disclosure_ceiling": "text",
      "expires_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_external_agent_task", order_by: "task_id", columns: {
      "task_id": "text",
      "operation_id": "text",
      "stage_index": "int",
      "stage": "text",
      "attempt_ref": "text",
      "request_sha256": "text",
      "project_id": "text",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "grantee_issuer": "text",
      "grantee_subject": "text",
      "state": "text",
      "lease_id": "text-or-null",
      "lease_slot": "text-or-null",
      "lease_credential_generation": "text-or-null",
      "lease_revision": "int",
      "lease_expires_at": "text-or-null",
      "result_idempotency_key": "text-or-null",
      "result_json": "text-or-null",
      "result_sha256": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_external_agent_task_progress", order_by: "task_id, cursor", columns: {
      "task_id": "text",
      "cursor": "int",
      "lease_id": "text",
      "credential_generation": "text",
      "progress_json": "text",
      "progress_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_external_agent_task_payload", order_by: "task_id", columns: {
      "task_id": "text",
      "task_kind": "text",
      "payload_json": "text",
      "payload_sha256": "text",
      "expires_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_computer_agent_route_binding", order_by: "operation_id", columns: {
      "operation_id": "text",
      "project_id": "text",
      "task_kind": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "actor_issuer": "text",
      "actor_subject": "text",
      "binding_json": "text",
      "binding_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "projects", table: "project_computer_agent_route", order_by: "project_id, task_kind, revision", columns: {
      "project_id": "text",
      "task_kind": "text",
      "revision": "int",
      "owner_principal_ref": "text",
      "state": "text",
      "strategy": "text",
      "connection_order_json": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
];
