import type { TableSpec } from "./coherent-cut.js";

// Generated from the complete ordered Core migration chain. Each column and
// stable primary-key order is explicit so additions fail the coverage gate.
export const DURABLE_CORE_TABLE_SPECS: readonly TableSpec[] = [
  { manifest: "purge", table: "purge_ledger", order_by: "ledger_revision", columns: {
      "ledger_revision": "int",
      "erasure_id": "text",
      "non_revealing_subject_digest": "text",
      "disposition": "text",
      "receipt_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_event", order_by: "investigation_id, sequence", columns: {
      "investigation_id": "text",
      "sequence": "int",
      "event_id": "text",
      "kind": "text",
      "payload_handle_ref": "text",
      "payload_digest": "text",
      "actor_ref": "text",
      "verifier_ref": "text-or-null",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_command", order_by: "command_id", columns: {
      "command_id": "text",
      "op_kind": "text",
      "expected_old_revision": "int",
      "expected_new_revision": "int",
      "expected_old_event_head": "int",
      "expected_new_event_head": "int",
      "expected_epoch": "int",
      "principal_ref": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "deployment_generation": "text",
      "global_purge_revision": "int",
      "scope_purge_revision": "int-or-null",
      "observed_at": "text",
      "expires_at": "text",
      "oh_investigation_id": "text-or-null",
      "oh_revision": "int-or-null",
      "oh_protocol_version": "text-or-null",
      "oh_goal": "text-or-null",
      "oh_scope_snapshot_id": "text-or-null",
      "oh_scope_snapshot_revision": "int-or-null",
      "oh_evidence_grade": "text-or-null",
      "oh_lane": "text-or-null",
      "oh_lane_registrations_json": "text-or-null",
      "oh_obligations_json": "text-or-null",
      "oh_hypotheses_json": "text-or-null",
      "oh_portfolio_ref": "text-or-null",
      "oh_debt_refs_json": "text-or-null",
      "oh_checkpoint_head": "int-or-null",
      "oh_principal_ref": "text-or-null",
      "oh_input_digest": "text-or-null",
      "oh_policy_generation": "text-or-null",
      "oh_policy_authority_ref": "text-or-null",
      "oh_deployment_generation": "text-or-null",
      "oh_idempotency_key": "text-or-null",
      "oh_model_profile_ref": "text-or-null",
      "oh_observed_execution": "text-or-null",
      "oh_observed_fidelity": "text-or-null",
      "oh_observed_assurance": "text-or-null",
      "oh_status": "text-or-null",
      "oh_supersedes_id": "text-or-null",
      "oh_supersession_reason": "text-or-null",
      "oh_event_head": "int-or-null",
      "oh_created_at": "text-or-null",
      "oh_updated_at": "text-or-null",
      "oe_investigation_id": "text-or-null",
      "oe_sequence": "int-or-null",
      "oe_event_id": "text-or-null",
      "oe_kind": "text-or-null",
      "oe_payload_handle_ref": "text-or-null",
      "oe_payload_digest": "text-or-null",
      "oe_actor_ref": "text-or-null",
      "oe_verifier_ref": "text-or-null",
      "oe_created_at": "text-or-null",
      "nh_investigation_id": "text",
      "nh_revision": "int",
      "nh_protocol_version": "text",
      "nh_goal": "text",
      "nh_scope_snapshot_id": "text",
      "nh_scope_snapshot_revision": "int",
      "nh_evidence_grade": "text",
      "nh_lane": "text",
      "nh_lane_registrations_json": "text",
      "nh_obligations_json": "text",
      "nh_hypotheses_json": "text",
      "nh_portfolio_ref": "text",
      "nh_debt_refs_json": "text",
      "nh_checkpoint_head": "int",
      "nh_principal_ref": "text",
      "nh_input_digest": "text",
      "nh_policy_generation": "text",
      "nh_policy_authority_ref": "text",
      "nh_deployment_generation": "text",
      "nh_idempotency_key": "text",
      "nh_model_profile_ref": "text",
      "nh_observed_execution": "text-or-null",
      "nh_observed_fidelity": "text-or-null",
      "nh_observed_assurance": "text-or-null",
      "nh_status": "text",
      "nh_supersedes_id": "text-or-null",
      "nh_supersession_reason": "text-or-null",
      "nh_event_head": "int",
      "nh_created_at": "text",
      "nh_updated_at": "text",
      "ne_investigation_id": "text",
      "ne_sequence": "int",
      "ne_event_id": "text",
      "ne_kind": "text",
      "ne_payload_handle_ref": "text",
      "ne_payload_digest": "text",
      "ne_actor_ref": "text",
      "ne_verifier_ref": "text-or-null",
      "ne_created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_head", order_by: "investigation_id", columns: {
      "investigation_id": "text",
      "revision": "int",
      "protocol_version": "text",
      "goal": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "evidence_grade": "text",
      "lane": "text",
      "lane_registrations_json": "text",
      "obligations_json": "text",
      "hypotheses_json": "text",
      "portfolio_ref": "text",
      "debt_refs_json": "text",
      "checkpoint_head": "int",
      "principal_ref": "text",
      "input_digest": "text",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "deployment_generation": "text",
      "idempotency_key": "text",
      "model_profile_ref": "text",
      "observed_execution": "text-or-null",
      "observed_fidelity": "text-or-null",
      "observed_assurance": "text-or-null",
      "status": "text",
      "supersedes_id": "text-or-null",
      "supersession_reason": "text-or-null",
      "event_head": "int",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_ledger_epoch", order_by: "singleton", columns: {
      "singleton": "int",
      "generation": "int"
  }, required: false },
  { manifest: "heads", table: "research_workflow_run", order_by: "operation_id", columns: {
      "operation_id": "text",
      "investigation_id": "text",
      "initial_revision": "int",
      "current_revision": "int",
      "principal_ref": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "authorization_receipt_ref": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "purge_revision": "int",
      "idempotency_key": "text",
      "handler_generation": "text",
      "initial_manifest_json": "text",
      "next_stage_index": "int",
      "state": "text",
      "cancellation_receipt_ref": "text-or-null",
      "created_at": "text",
      "first_failure_json": "text-or-null",
      "latest_failure_json": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_workflow_attempt", order_by: "operation_id, stage_index", columns: {
      "operation_id": "text",
      "stage_index": "int",
      "request_json": "text",
      "request_sha256": "text",
      "attempt_ref": "text",
      "expected_revision": "int",
      "budget_receipt_ref": "text",
      "budget_expires_at_ms": "int",
      "state": "text",
      "output_json": "text-or-null",
      "created_at": "text",
      "first_failure_json": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_workflow_checkpoint", order_by: "operation_id, stage_index", columns: {
      "operation_id": "text",
      "stage_index": "int",
      "request_sha256": "text",
      "receipt_json": "text",
      "receipt_sha256": "text",
      "ledger_event_id": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_workflow_citation_binding", order_by: "operation_id, stage_index", columns: {
      "operation_id": "text",
      "stage_index": "int",
      "attempt_ref": "text",
      "request_sha256": "text",
      "receipt_id": "text",
      "receipt_revision": "int",
      "receipt_sha256": "text",
      "bound_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_query_result", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "state": "text",
      "result_json": "text-or-null",
      "result_digest": "text-or-null",
      "trace_id": "text-or-null",
      "trace_revision": "int-or-null",
      "coverage_claim": "text",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_query_trace", order_by: "trace_id, revision", columns: {
      "trace_id": "text",
      "revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "trace_json": "text",
      "trace_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_exhaustive_job", order_by: "job_id", columns: {
      "job_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "scope_digest": "text",
      "plan_id": "text",
      "coverage_denominator_ref": "text",
      "denominator_shard_ids_json": "text",
      "state": "text",
      "denominator_shards": "int",
      "settled_shards": "int-or-null",
      "total_scanned_sections": "int-or-null",
      "total_matches": "int-or-null",
      "result_artifact_ref": "text-or-null",
      "coverage_receipt_ref": "text-or-null",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_exhaustive_shard", order_by: "job_id, shard_id", columns: {
      "job_id": "text",
      "shard_id": "text",
      "outcome_json": "text",
      "outcome_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "retrieval_exhaustive_workflow", order_by: "workflow_id", columns: {
      "workflow_id": "text",
      "job_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "request_identity_digest": "text",
      "state": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "raw_file_capture", order_by: "capture_id", columns: {
      "capture_id": "text",
      "principal_ref": "text",
      "owner_system_id": "text",
      "source_namespace_id": "text",
      "source_revision_ref": "text",
      "source_logical_id": "text",
      "source_owner_generation": "text",
      "idempotency_key": "text",
      "original_file_name": "text",
      "request_digest": "text",
      "residency_key_json": "text",
      "residency_key_digest": "text",
      "content_sha256": "text",
      "size_bytes": "int",
      "content_type": "text",
      "state": "text",
      "object_key": "text",
      "receipt_json": "text-or-null",
      "receipt_sha256": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "expires_at": "text",
      "target_source_id": "text-or-null",
      "expected_head_revision_ref": "text-or-null"
  }, required: false },
  { manifest: "sources", table: "raw_markdown_conversion", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "capture_id": "text",
      "content_sha256": "text",
      "size_bytes": "int",
      "request_sha256": "text",
      "request_json": "text",
      "authority_sha256": "text",
      "attempt_id": "text",
      "state": "text",
      "result_json": "text-or-null",
      "result_sha256": "text-or-null",
      "output_object_key": "text",
      "receipt_object_key": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "sources", table: "raw_normalized_admission", order_by: "admission_operation_id", columns: {
      "admission_operation_id": "text",
      "principal_ref": "text",
      "capture_id": "text",
      "conversion_operation_id": "text",
      "idempotency_key": "text",
      "input_fingerprint": "text",
      "candidate_ref": "text",
      "source_revision_ref": "text",
      "source_view_ref": "text",
      "snapshot_view_json": "text",
      "snapshot_view_sha256": "text",
      "policy_snapshot_json": "text",
      "policy_snapshot_sha256": "text",
      "policy_revision": "int",
      "ingest_operation_id": "text-or-null",
      "state": "text",
      "reason_codes_json": "text",
      "receipt_json": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "sources", table: "workspace_mcp_observation", order_by: "observation_id", columns: {
      "observation_id": "text",
      "plan_id": "text",
      "principal_ref": "text",
      "deployment_generation": "text",
      "auth_profile": "text",
      "google_transport": "text",
      "idempotency_key": "text",
      "receipt_sha256": "text",
      "receipt_json": "text",
      "observation_json": "text",
      "observation_sha256": "text",
      "disposition": "text",
      "reason_codes_json": "text",
      "observed_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "workspace_mcp_raw_normalized_admission", order_by: "binding_id", columns: {
      "binding_id": "text",
      "principal_ref": "text",
      "deployment_generation": "text",
      "auth_profile": "text",
      "google_transport": "text",
      "idempotency_key": "text",
      "plan_idempotency_key": "text",
      "plan_id": "text",
      "plan_sha256": "text",
      "observation_id": "text",
      "observation_receipt_sha256": "text",
      "capture_id": "text",
      "capture_content_sha256": "text",
      "conversion_operation_id": "text",
      "admission_operation_id": "text-or-null",
      "state": "text",
      "created_at": "text",
      "updated_at": "text",
      "observation_principal_ref": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_reservation", order_by: "intent_id, intent_revision", columns: {
      "intent_id": "text",
      "intent_revision": "int",
      "artifact_id": "text",
      "artifact_revision": "int",
      "request_sha256": "text",
      "spec_digest": "text",
      "manifest_r2_key": "text",
      "expected_head_revision": "int-or-null",
      "spec_ref_id": "text",
      "spec_ref_revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "intent_json": "text",
      "principal_ref": "text",
      "idempotency_key": "text",
      "payload_ref": "text",
      "topic": "text",
      "planned_objects_json": "text",
      "state": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_head", order_by: "artifact_id", columns: {
      "artifact_id": "text",
      "head_revision": "int",
      "manifest_r2_key": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_binding", order_by: "artifact_id, revision", columns: {
      "artifact_id": "text",
      "revision": "int",
      "intent_id": "text",
      "intent_revision": "int",
      "expected_head_revision": "int-or-null",
      "principal_ref": "text",
      "spec_ref_id": "text",
      "spec_ref_revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "manifest_r2_key": "text",
      "manifest_sha256": "text",
      "manifest_size_bytes": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_draft_object", order_by: "artifact_id, revision, object_kind, object_ref", columns: {
      "artifact_id": "text",
      "revision": "int",
      "object_kind": "text",
      "object_ref": "text",
      "section_ordinal": "int-or-null",
      "receipt_json": "text",
      "residency_key_json": "text",
      "residency_key_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_model_attempt", order_by: "attempt_id", columns: {
      "attempt_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "reservation_id": "text",
      "attempt_number": "int",
      "principal_ref": "text",
      "operation_kind": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "request_json": "text",
      "authority_json": "text",
      "route_ref": "text",
      "prompt_generation": "text",
      "schema_generation": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "state": "text",
      "receipt_json": "text-or-null",
      "receipt_sha256": "text-or-null",
      "output_object_ref": "text-or-null",
      "output_sha256": "text-or-null",
      "output_size_bytes": "int-or-null",
      "readback_sha256": "text-or-null",
      "error_code": "text-or-null",
      "reason_codes_json": "text",
      "started_at": "text",
      "ended_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_reference_manifest", order_by: "manifest_id, manifest_revision", columns: {
      "manifest_id": "text",
      "manifest_revision": "int",
      "manifest_digest": "text",
      "r2_content_sha256": "text",
      "r2_residency_key_json": "text",
      "r2_residency_key_digest": "text",
      "r2_key": "text",
      "r2_etag": "text",
      "r2_size_bytes": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "scope_snapshot_digest": "text",
      "policy_authority_ref": "text",
      "authorization_receipt_ref": "text",
      "principal_ref": "text",
      "credential_generation": "text",
      "pack_ref_id": "text",
      "pack_ref_revision": "int",
      "trace_ref_id": "text",
      "trace_ref_revision": "int",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "state": "text",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_model_fingerprint", order_by: "observation_seq", columns: {
      "observation_seq": "int",
      "fingerprint_ref": "text",
      "route_ref": "text",
      "fingerprint_sha256": "text",
      "fingerprint_json": "text",
      "observed_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_model_output", order_by: "output_object_ref", columns: {
      "output_object_ref": "text",
      "attempt_id": "text",
      "principal_ref": "text",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "request_sha256": "text",
      "workflow_budget_receipt_ref": "text",
      "residency_domain_json": "text",
      "residency_domain_sha256": "text",
      "r2_key": "text-or-null",
      "r2_etag": "text-or-null",
      "output_sha256": "text-or-null",
      "output_size_bytes": "int-or-null",
      "readback_sha256": "text-or-null",
      "state": "text",
      "created_at": "text",
      "committed_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_model_pricing_snapshot", order_by: "pricing_snapshot_ref", columns: {
      "pricing_snapshot_ref": "text",
      "route_ref": "text",
      "route_version": "text",
      "provider": "text",
      "exact_model_id": "text",
      "pricing_basis": "text",
      "input_rate_usd_per_1k_tokens": "text",
      "output_rate_usd_per_1k_tokens": "text",
      "provenance_ref": "text",
      "approval_receipt_ref": "text",
      "effective_at": "text",
      "expires_at": "text",
      "snapshot_sha256": "text",
      "snapshot_json": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_candidate", order_by: "candidate_ref", columns: {
      "candidate_ref": "text",
      "route_ref": "text",
      "route_version": "text",
      "candidate_sha256": "text",
      "candidate_json": "text",
      "staged_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_active_generation", order_by: "route_ref", columns: {
      "route_ref": "text",
      "route_version": "text",
      "candidate_ref": "text",
      "candidate_sha256": "text",
      "promotion_ref": "text",
      "promoted_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_qualification_proof", order_by: "qualification_ref", columns: {
      "qualification_ref": "text",
      "proof_sha256": "text",
      "qualification_json": "text",
      "route_ref": "text",
      "route_version": "text",
      "candidate_ref": "text",
      "candidate_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "generations", table: "dynamic_route_active_qualification", order_by: "route_ref, route_version", columns: {
      "route_ref": "text",
      "route_version": "text",
      "candidate_ref": "text",
      "candidate_sha256": "text",
      "qualification_ref": "text",
      "qualification_sha256": "text",
      "activated_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_proposal", order_by: "proposal_id, proposal_revision", columns: {
      "proposal_id": "text",
      "proposal_revision": "int",
      "principal_ref": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "page_id": "text",
      "page_revision": "int",
      "page_sha256": "text",
      "page_json": "text",
      "risk_class": "text",
      "body_size": "int",
      "evidence_map_sha256": "text",
      "evidence_map_size": "int",
      "dependency_refs_sha256": "text",
      "state": "text",
      "created_at": "text",
      "published_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_authority", order_by: "proposal_id, proposal_revision", columns: {
      "proposal_id": "text",
      "proposal_revision": "int",
      "evidence_receipt_ref": "text",
      "coverage_receipt_json": "text",
      "dependency_closure_receipt_ref": "text",
      "verifier_receipt_ref": "text",
      "policy_receipt_ref": "text-or-null",
      "coverage_complete": "int",
      "dependency_closure_complete": "int",
      "conflict_count": "int",
      "changes_current_state": "int",
      "state": "text",
      "admitted_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_revision", order_by: "page_id, revision", columns: {
      "page_id": "text",
      "revision": "int",
      "proposal_id": "text",
      "proposal_revision": "int",
      "manifest_ref": "text",
      "page_sha256": "text",
      "page_json": "text",
      "body_object_ref": "text",
      "body_sha256": "text",
      "committer_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_head", order_by: "page_id", columns: {
      "page_id": "text",
      "revision": "int",
      "manifest_ref": "text",
      "outbox_ref": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "wiki_publication_outbox", order_by: "outbox_ref", columns: {
      "outbox_ref": "text",
      "page_id": "text",
      "revision": "int",
      "manifest_ref": "text",
      "payload_sha256": "text",
      "state": "text",
      "created_at": "text",
      "delivered_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "wiki_owner_edit_binding", order_by: "proposal_id, proposal_revision", columns: {
      "proposal_id": "text",
      "proposal_revision": "int",
      "principal_ref": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "proposal_page_sha256": "text",
      "base_proposal_id": "text",
      "base_proposal_revision": "int",
      "base_page_id": "text",
      "base_page_revision": "int",
      "base_page_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "ownership", table: "source_namespace_initialization", order_by: "source_namespace_id", columns: {
      "source_namespace_id": "text",
      "principal_ref": "text",
      "credential_generation": "text",
      "profile_id": "text",
      "profile_revision": "int",
      "title": "text",
      "idempotency_key": "text",
      "owner_incarnation_ref": "text",
      "source_owner_generation": "text",
      "ownership_record_revision": "int",
      "source_admission_policy_revision": "int",
      "scope_policy_ref": "text",
      "scope_policy_generation": "int",
      "request_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "raw_ingest_erasure_member", order_by: "source_revision_ref, member_kind, member_id", columns: {
      "source_revision_ref": "text",
      "member_kind": "text",
      "member_id": "text"
  }, required: false },
  { manifest: "generations", table: "model_route_qualification_probe", order_by: "probe_idempotency_key", columns: {
      "probe_idempotency_key": "text",
      "probe_input_sha256": "text",
      "claim_ref": "text",
      "started_at": "text",
      "execution_probe_ref": "text-or-null",
      "observation_sha256": "text-or-null",
      "observation_json": "text-or-null"
  }, required: false },
  { manifest: "generations", table: "model_route_qualification_dispatch", order_by: "probe_idempotency_key", columns: {
      "probe_idempotency_key": "text",
      "probe_input_sha256": "text",
      "claim_ref": "text",
      "state": "text",
      "observation_sha256": "text-or-null",
      "observation_json": "text-or-null",
      "started_at": "text",
      "completed_at": "text-or-null"
  }, required: false },
  { manifest: "projects", table: "project_mutation_guard", order_by: "principal_ref, idempotency_key", columns: {
      "principal_ref": "text",
      "idempotency_key": "text",
      "operation": "text",
      "project_id": "text",
      "expected_revision": "int",
      "next_revision": "int",
      "created_at": "text",
      "project_client_grant_id": "text-or-null",
      "project_client_grant_revision": "int-or-null",
      "client_authority_expires_at": "text-or-null"
  }, required: false },
  { manifest: "projects", table: "project_mutation_receipt", order_by: "principal_ref, idempotency_key", columns: {
      "principal_ref": "text",
      "idempotency_key": "text",
      "operation": "text",
      "project_id": "text",
      "request_sha256": "text",
      "response_json": "text",
      "response_sha256": "text",
      "project_revision": "int",
      "deployment_generation": "text",
      "created_at": "text",
      "project_client_grant_id": "text-or-null",
      "project_client_grant_revision": "int-or-null",
      "client_authority_expires_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "research_report_admission", order_by: "decision_id", columns: {
      "decision_id": "text",
      "decision_revision": "int",
      "decision": "text",
      "decision_json": "text",
      "decision_sha256": "text",
      "input_json": "text",
      "input_sha256": "text",
      "policy_json": "text",
      "policy_ref": "text",
      "policy_revision": "int",
      "policy_generation": "text",
      "policy_authority_ref": "text",
      "policy_expires_at": "text",
      "operation_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "outbox_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "scope_snapshot_digest": "text",
      "authorization_receipt_ref": "text",
      "deployment_generation": "text",
      "source_revision_refs_json": "text",
      "requested_output_class": "text",
      "purpose": "text",
      "disclosure_ceiling": "text",
      "expires_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_external_agent_task", order_by: "task_id", columns: {
      "task_id": "text",
      "operation_id": "text",
      "stage_index": "int",
      "stage": "text",
      "attempt_ref": "text",
      "request_sha256": "text",
      "project_id": "text",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "grantee_issuer": "text",
      "grantee_subject": "text",
      "state": "text",
      "lease_id": "text-or-null",
      "lease_slot": "text-or-null",
      "lease_credential_generation": "text-or-null",
      "lease_revision": "int",
      "lease_expires_at": "text-or-null",
      "result_idempotency_key": "text-or-null",
      "result_json": "text-or-null",
      "result_sha256": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_external_agent_task_progress", order_by: "task_id, cursor", columns: {
      "task_id": "text",
      "cursor": "int",
      "lease_id": "text",
      "credential_generation": "text",
      "progress_json": "text",
      "progress_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_external_agent_task_payload", order_by: "task_id", columns: {
      "task_id": "text",
      "task_kind": "text",
      "payload_json": "text",
      "payload_sha256": "text",
      "expires_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_computer_agent_route_binding", order_by: "operation_id", columns: {
      "operation_id": "text",
      "project_id": "text",
      "task_kind": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "actor_issuer": "text",
      "actor_subject": "text",
      "binding_json": "text",
      "binding_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "projects", table: "project_computer_agent_route", order_by: "project_id, task_kind, revision", columns: {
      "project_id": "text",
      "task_kind": "text",
      "revision": "int",
      "owner_principal_ref": "text",
      "state": "text",
      "strategy": "text",
      "connection_order_json": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "projects", table: "project_computer_agent_route_entry", order_by: "project_id, task_kind, route_revision, priority", columns: {
      "project_id": "text",
      "task_kind": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "project_id": "text",
      "task_kind": "text",
      "transport": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "actor_issuer": "text",
      "actor_subject": "text",
      "qualification_challenge_id": "text",
      "qualification_observation_ref": "text",
      "qualification_credential_generation": "text",
      "deployment_generation": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "run_request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_acceptance", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "workflow_instance_id": "text",
      "investigation_id": "text",
      "investigation_revision": "int",
      "actor_issuer": "text",
      "actor_subject": "text",
      "credential_generation": "text",
      "record_json": "text",
      "record_sha256": "text",
      "accepted_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_abandonment", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "project_id": "text",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "reason": "text",
      "note": "text-or-null",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "abandoned_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_decline", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "project_id": "text",
      "connection_id": "text",
      "connection_revision": "int",
      "actor_issuer": "text",
      "actor_subject": "text",
      "credential_generation": "text",
      "reason": "text",
      "note": "text-or-null",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "declined_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_reassignment", order_by: "predecessor_dispatch_id", columns: {
      "predecessor_dispatch_id": "text",
      "successor_dispatch_id": "text",
      "project_id": "text",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "predecessor_state": "text",
      "run_request_sha256": "text",
      "successor_transport": "text",
      "successor_route_revision": "int",
      "successor_connection_id": "text",
      "successor_connection_revision": "int",
      "successor_client_grant_id": "text",
      "successor_client_grant_revision": "int",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "reassigned_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_preferred_dispatch_selection", order_by: "selection_id", columns: {
      "selection_id": "text",
      "project_id": "text",
      "task_kind": "text",
      "selection_strategy": "text",
      "transport": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "qualification_challenge_id": "text",
      "qualification_observation_ref": "text",
      "qualification_credential_generation": "text",
      "qualification_ready_until": "text",
      "deployment_generation": "text",
      "run_request_sha256": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "selected_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_preferred_dispatch_settlement", order_by: "selection_id", columns: {
      "selection_id": "text",
      "dispatch_id": "text",
      "record_json": "text",
      "record_sha256": "text",
      "settled_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_model_spend_admission", order_by: "operation_id, stage_index", columns: {
      "authorization_ref": "text",
      "operation_id": "text",
      "workflow_operation_id": "text",
      "stage_index": "int",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "stage_request_json": "text",
      "workflow_budget_receipt_ref": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "intent_json": "text",
      "reservation_id": "text",
      "quote_ref": "text",
      "quote_json": "text",
      "authority_json": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "policy_decision_ref": "text",
      "policy_generation": "text",
      "currentness_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "workflow_authorization_receipt_ref": "text",
      "route_ref": "text",
      "expected_deployment_json": "text",
      "approval_json": "text",
      "admission_revision": "int",
      "admission_sha256": "text",
      "decision_digest": "text",
      "max_input_bytes": "int",
      "max_output_bytes": "int",
      "expires_at": "text",
      "created_at": "text",
      "role": "text-or-null"
  }, required: false },
  { manifest: "generations", table: "research_semantic_config_revision", order_by: "revision_ref", columns: {
      "revision_ref": "text",
      "config_sha256": "text",
      "config_json": "text",
      "byte_length": "int",
      "protocol": "text",
      "created_at": "text",
      "created_by_principal_ref": "text"
  }, required: false },
  { manifest: "purge", table: "operation_intent", order_by: "intent_id, revision", columns: {
      "intent_id": "text",
      "revision": "int",
      "operation_kind": "text",
      "principal_ref": "text",
      "idempotency_key": "text",
      "payload_ref": "text",
      "policy_decision_ref": "text",
      "budget_reservation_ref": "text-or-null",
      "cancellation_ref": "text-or-null",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "operation_attempt", order_by: "attempt_id", columns: {
      "attempt_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "attempt_number": "int",
      "state": "text",
      "checkpoint_ref": "text-or-null",
      "error_code": "text-or-null",
      "started_at": "text",
      "ended_at": "text-or-null"
  }, required: false },
  { manifest: "purge", table: "operation_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "intent_id": "text",
      "intent_revision": "int",
      "attempt_id": "text",
      "outcome": "text",
      "output_refs_json": "text",
      "readback_receipt_refs_json": "text",
      "reconciliation_required": "int",
      "reason_codes_json": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "outbox", order_by: "outbox_id", columns: {
      "outbox_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "topic": "text",
      "payload_ref": "text",
      "state": "text",
      "attempts": "int",
      "next_attempt_at": "int",
      "lease_owner": "text-or-null",
      "lease_until": "int-or-null",
      "queue_message_id": "text-or-null",
      "last_error_code": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "payload_sha256": "text-or-null",
      "lease_generation": "int"
  }, required: false },
  { manifest: "purge", table: "job", order_by: "job_id", columns: {
      "job_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "state": "text",
      "current_stage": "text-or-null",
      "progress_cursor": "text-or-null",
      "workflow_instance_id": "text-or-null",
      "terminal_receipt_ref": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "delivery_inbox", order_by: "message_id", columns: {
      "message_id": "text",
      "idempotency_key": "text",
      "topic": "text",
      "payload_ref": "text",
      "state": "text",
      "attempt": "int",
      "lease_owner": "text-or-null",
      "lease_generation": "int",
      "lease_until": "int-or-null",
      "result_receipt_ref": "text-or-null",
      "last_error_code": "text-or-null",
      "first_seen_at": "int",
      "updated_at": "int",
      "payload_sha256": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "investigation_event", order_by: "investigation_id, sequence", columns: {
      "investigation_id": "text",
      "sequence": "int",
      "event_id": "text",
      "kind": "text",
      "payload_ref": "text",
      "actor_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_checkpoint", order_by: "investigation_id, investigation_revision, stage, checkpoint_ref", columns: {
      "investigation_id": "text",
      "investigation_revision": "int",
      "stage": "text",
      "checkpoint_ref": "text",
      "input_manifest_ref": "text",
      "output_manifest_ref": "text",
      "idempotency_key": "text",
      "budget_receipt_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "evidence_freeze", order_by: "freeze_id, revision", columns: {
      "freeze_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "investigation_revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "coverage_denominator_ref": "text",
      "contract_protocol_digest": "text",
      "lane_digest": "text",
      "manifest_r2_key": "text",
      "frozen_at": "text",
      "superseded_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "claim_audit", order_by: "audit_id, revision", columns: {
      "audit_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "investigation_revision": "int",
      "evidence_freeze_id": "text",
      "evidence_freeze_revision": "int",
      "manifest_r2_key": "text",
      "material_claim_count": "int",
      "failed_claim_count": "int",
      "unresolved_precision_count": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "coverage_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "investigation_revision": "int",
      "denominator_kind": "text",
      "eligible_count": "int",
      "represented_count": "int",
      "cited_count": "int",
      "terminal_disposition": "text",
      "manifest_r2_key": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_debt", order_by: "debt_id, revision", columns: {
      "debt_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "kind": "text",
      "blocking_effect": "text",
      "next_probe": "text",
      "owner_ref": "text",
      "status": "text",
      "manifest_r2_key": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "budget_reservation", order_by: "reservation_id", columns: {
      "reservation_id": "text",
      "operation_kind": "text",
      "project_id": "text-or-null",
      "platform_usd": "real",
      "workers_ai_usd": "real",
      "byok_usd": "real",
      "max_total_usd": "real",
      "workflow_steps": "int",
      "state": "text",
      "expires_at": "text",
      "created_at": "text",
      "principal_ref": "text-or-null",
      "idempotency_key": "text-or-null",
      "request_sha256": "text-or-null",
      "request_json": "text-or-null",
      "policy_decision_ref": "text-or-null",
      "credential_generation": "text-or-null",
      "deployment_generation": "text-or-null",
      "quote_ref": "text-or-null",
      "expected_sources": "int-or-null",
      "expected_sections": "int-or-null",
      "confidence": "real-or-null",
      "quote_json": "text-or-null",
      "authority_json": "text-or-null",
      "stage_attempt_ref": "text-or-null",
      "stage_request_sha256": "text-or-null"
  }, required: false },
  { manifest: "purge", table: "erasure_case", order_by: "erasure_id, revision", columns: {
      "erasure_id": "text",
      "revision": "int",
      "state": "text",
      "exact_subject_refs_json": "text",
      "requested_locations_json": "text",
      "completed_locations_json": "text",
      "blocked_locations_json": "text",
      "legal_basis_ref": "text",
      "deadline": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_execution", order_by: "erasure_id, revision", columns: {
      "erasure_id": "text",
      "revision": "int",
      "request_json": "text",
      "request_sha256": "text",
      "state": "text",
      "lease_owner": "text-or-null",
      "lease_generation": "int",
      "lease_until": "int-or-null",
      "closure_digest": "text-or-null",
      "terminal_receipt_json": "text-or-null",
      "terminal_receipt_sha256": "text-or-null",
      "purge_ledger_revision": "int-or-null",
      "last_error_code": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_dependency_registry", order_by: "dependency_id", columns: {
      "dependency_id": "text",
      "exact_subject_ref": "text",
      "location": "text",
      "canonical_ref": "text",
      "provider_ref": "text-or-null",
      "object_identity_digest": "text",
      "shared_reference_key": "text-or-null",
      "retention_or_hold_ref": "text-or-null",
      "next_review_at": "text-or-null",
      "declassification_receipt_ref": "text-or-null",
      "state": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_target", order_by: "erasure_id, erasure_revision, target_id", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "target_id": "text",
      "target_kind": "text",
      "exact_subject_ref": "text",
      "location": "text",
      "canonical_ref": "text",
      "provider_ref": "text-or-null",
      "identity_digest": "text",
      "shared_live_reference_count": "int",
      "retention_or_hold_ref": "text-or-null",
      "next_review_at": "text-or-null",
      "state": "text",
      "delete_receipt_ref": "text-or-null",
      "absence_receipt_ref": "text-or-null",
      "last_error_code": "text-or-null",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_stage_receipt", order_by: "erasure_id, erasure_revision, stage", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "stage": "text",
      "lease_generation": "int",
      "receipt_ref": "text",
      "payload_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_dependent_invalidation", order_by: "erasure_id, erasure_revision, dependent_ref", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "dependent_ref": "text",
      "dependent_kind": "text",
      "disposition": "text",
      "receipt_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_terminal_guard", order_by: "erasure_id, erasure_revision", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "closure_digest": "text",
      "requested_locations_json": "text",
      "completed_locations_json": "text",
      "blocked_locations_json": "text",
      "terminal_state": "text",
      "receipt_sha256": "text",
      "purge_ledger_revision": "int",
      "verified": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "backup_purge_obligation", order_by: "erasure_id, erasure_revision, backup_epoch_id", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "backup_epoch_id": "text",
      "target_id": "text",
      "state": "text",
      "policy_or_hold_ref": "text-or-null",
      "next_review_at": "text-or-null",
      "delete_receipt_ref": "text-or-null",
      "absence_receipt_ref": "text-or-null",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_admission_request", order_by: "erasure_id, erasure_revision", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "permission_ref": "text",
      "permission_revision": "int",
      "principal_ref": "text",
      "credential_generation": "text",
      "permission_sha256": "text",
      "request_json": "text",
      "request_sha256": "text",
      "request_identity_sha256": "text",
      "admitted_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "federation_reference_manifest", order_by: "manifest_id, revision", columns: {
      "manifest_id": "text",
      "revision": "int",
      "manifest_json": "text",
      "manifest_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "client_fence_ref": "text-or-null",
      "expires_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "federation_job", order_by: "job_id", columns: {
      "job_id": "text",
      "exchange_id": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "request_json": "text",
      "requester_principal_ref": "text",
      "requester_credential_generation": "text",
      "server_principal_ref": "text",
      "server_credential_generation": "text",
      "bridge_generation": "text",
      "client_fence_ref": "text",
      "allowed_manifest_id": "text",
      "allowed_manifest_revision": "int",
      "origin_trace_id": "text",
      "attempt": "int",
      "transport_state": "text",
      "status_json": "text",
      "observed_completion_disposition": "text-or-null",
      "result_json": "text-or-null",
      "cancellation_reason": "text-or-null",
      "cancelled_at": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "navigation_artifact", order_by: "scope_snapshot_id, scope_snapshot_revision, artifact_kind, subject_id, subject_revision", columns: {
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "artifact_kind": "text",
      "subject_id": "text",
      "subject_revision": "int",
      "artifact_id": "text",
      "artifact_revision": "int",
      "body_digest": "text",
      "body_json": "text",
      "source_bindings_json": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "bundle_ingest_operation", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "origin_authentication_receipt_ref": "text",
      "idempotency_key": "text",
      "input_fingerprint": "text",
      "manifest_sha256": "text",
      "manifest_json": "text",
      "file_hashes_json": "text",
      "total_bytes": "int",
      "source_namespace_id": "text",
      "owner_system_id": "text",
      "source_owner_generation": "text",
      "source_revision_ref": "text",
      "source_id": "text",
      "expected_head_revision_ref": "text-or-null",
      "residency_key_json": "text",
      "residency_key_digest": "text",
      "policy_revision": "int",
      "policy_snapshot_json": "text",
      "policy_snapshot_sha256": "text",
      "candidate_id": "text",
      "staging_session_ref": "text-or-null",
      "qualification_report_ref": "text-or-null",
      "decision_receipt_ref": "text-or-null",
      "promotion_receipt_ref": "text-or-null",
      "state": "text",
      "bundle_receipt_json": "text-or-null",
      "bundle_receipt_sha256": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "expires_at": "text",
      "client_origin_json": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "bundle_ingest_commit_guard", order_by: "operation_id", columns: {
      "operation_id": "text",
      "source_revision_ref": "text",
      "ingest_receipt_id": "text",
      "ingest_receipt_revision": "int",
      "projection_intent_id": "text",
      "projection_intent_revision": "int",
      "outbox_id": "text",
      "verified": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "source_acquisition_candidate", order_by: "candidate_id, revision", columns: {
      "candidate_id": "text",
      "revision": "int",
      "operation_id": "text",
      "observed_locator_identifier_or_upload_ref": "text",
      "proposer_principal_ref": "text",
      "proposer_run_ref": "text-or-null",
      "allowed_reference_manifest_id": "text-or-null",
      "allowed_reference_manifest_revision": "int-or-null",
      "proposed_source_class": "text",
      "purpose": "text",
      "requested_scope_expression_json": "text",
      "untrusted_metadata_json": "text",
      "staging_object_ref": "text-or-null",
      "policy_refs_json": "text",
      "state": "text",
      "effect_ceiling": "text",
      "created_at": "text",
      "expires_at": "text",
      "terminal_receipt_ref": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "qualification_report", order_by: "report_id, revision", columns: {
      "report_id": "text",
      "revision": "int",
      "operation_id": "text",
      "source_revision_ref": "text",
      "parser_profile_generation": "text",
      "checks_json": "text",
      "overall": "text",
      "exact_precision_ceiling": "text",
      "warnings_json": "text",
      "report_json": "text",
      "report_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "source_admission_decision", order_by: "decision_receipt_ref", columns: {
      "decision_receipt_ref": "text",
      "operation_id": "text",
      "source_namespace_id": "text",
      "owner_system_id": "text",
      "source_owner_generation": "text",
      "source_revision_ref": "text",
      "origin_authentication_receipt_ref": "text",
      "source_class": "text",
      "assurance_ceiling": "text",
      "instruction_taint": "text",
      "allowed_effects": "text",
      "object_residency_key_digest": "text",
      "allowed_use_json": "text",
      "disclosure_ceiling": "text",
      "license_policy_ref": "text",
      "expires_at": "text-or-null",
      "decision": "text",
      "reason_codes_json": "text",
      "decision_json": "text",
      "decision_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "drive_observation", order_by: "generation_id, object_kind, object_id, content_sha256", columns: {
      "generation_id": "text",
      "object_kind": "text",
      "object_id": "text",
      "idempotency_key": "text-or-null",
      "content_sha256": "text",
      "observed_row": "int",
      "drive_modified_time": "text",
      "actor_claim": "text-or-null",
      "frozen_r2_key": "text",
      "disposition": "text",
      "imported_at": "text"
  }, required: false },
  { manifest: "heads", table: "incident", order_by: "incident_id", columns: {
      "incident_id": "text",
      "severity": "text",
      "kind": "text",
      "state": "text",
      "details_ref": "text",
      "created_at": "text",
      "resolved_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "evidence_resolution_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "handle_id": "text",
      "handle_revision": "int",
      "source_revision_ref": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "authorization_receipt_ref": "text",
      "normalized_object_ref": "text",
      "normalized_object_ref_digest": "text",
      "source_revision_content_sha256": "text",
      "source_object_size": "int",
      "scope_snapshot_digest": "text",
      "anchor_digest": "text",
      "excerpt_sha256": "text",
      "excerpt_byte_length": "int",
      "source_owner_generation": "text",
      "purge_state": "text",
      "terminal_state": "text",
      "receipt_json": "text",
      "receipt_sha256": "text",
      "resolved_at": "text"
  }, required: false },
  { manifest: "heads", table: "citation_resolution_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "authorization_receipt_ref": "text",
      "requested_handle_refs_json": "text",
      "resolved_json": "text",
      "rejected_json": "text",
      "requested_count": "int",
      "resolved_count": "int",
      "all_material_citations_resolved": "int",
      "receipt_json": "text",
      "receipt_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "orientation_request", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "state": "text",
      "snapshot_id": "text-or-null",
      "snapshot_revision": "int-or-null",
      "result_json": "text-or-null",
      "result_digest": "text-or-null",
      "created_at": "text",
      "expires_at": "text",
      "execution_operation_id": "text-or-null",
      "execution_client_grant_id": "text-or-null",
      "execution_client_grant_revision": "int-or-null"
  }, required: false },
  { manifest: "heads", table: "orientation_authority_epoch", order_by: "singleton", columns: {
      "singleton": "int",
      "generation": "int"
  }, required: false },
  { manifest: "heads", table: "google_oauth_intent_receipt", order_by: "intent_id", columns: {
      "intent_id": "text",
      "operation_ref": "text",
      "principal_id": "text",
      "configuration_json": "text",
      "state_sha256": "text",
      "terminal_state": "text",
      "terminal_at": "text",
      "retained_at": "text"
  }, required: false },
];
