import type { TableSpec } from "./coherent-cut.js";

// Explicit PRAGMA-derived columns and deterministic primary-key ordering.
export const DURABLE_CORE_TABLE_SPECS_C: readonly TableSpec[] = [
  { manifest: "projects", table: "project_computer_agent_route_entry", order_by: "project_id, task_kind, route_revision, priority", columns: {
      "project_id": "text",
      "task_kind": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "project_id": "text",
      "task_kind": "text",
      "transport": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "actor_issuer": "text",
      "actor_subject": "text",
      "qualification_challenge_id": "text",
      "qualification_observation_ref": "text",
      "qualification_credential_generation": "text",
      "deployment_generation": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "run_request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "created_at": "text",
      "expires_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_acceptance", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "workflow_instance_id": "text",
      "investigation_id": "text",
      "investigation_revision": "int",
      "actor_issuer": "text",
      "actor_subject": "text",
      "credential_generation": "text",
      "record_json": "text",
      "record_sha256": "text",
      "accepted_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_abandonment", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "project_id": "text",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "reason": "text",
      "note": "text-or-null",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "abandoned_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_decline", order_by: "dispatch_id", columns: {
      "dispatch_id": "text",
      "project_id": "text",
      "connection_id": "text",
      "connection_revision": "int",
      "actor_issuer": "text",
      "actor_subject": "text",
      "credential_generation": "text",
      "reason": "text",
      "note": "text-or-null",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "declined_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_dispatch_reassignment", order_by: "predecessor_dispatch_id", columns: {
      "predecessor_dispatch_id": "text",
      "successor_dispatch_id": "text",
      "project_id": "text",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "predecessor_state": "text",
      "run_request_sha256": "text",
      "successor_transport": "text",
      "successor_route_revision": "int",
      "successor_connection_id": "text",
      "successor_connection_revision": "int",
      "successor_client_grant_id": "text",
      "successor_client_grant_revision": "int",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "reassigned_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_preferred_dispatch_selection", order_by: "selection_id", columns: {
      "selection_id": "text",
      "project_id": "text",
      "task_kind": "text",
      "selection_strategy": "text",
      "transport": "text",
      "route_revision": "int",
      "priority": "int",
      "connection_id": "text",
      "connection_revision": "int",
      "client_grant_id": "text",
      "client_grant_revision": "int",
      "owner_principal_ref": "text",
      "owner_credential_generation": "text",
      "qualification_challenge_id": "text",
      "qualification_observation_ref": "text",
      "qualification_credential_generation": "text",
      "qualification_ready_until": "text",
      "deployment_generation": "text",
      "run_request_sha256": "text",
      "idempotency_key": "text",
      "request_sha256": "text",
      "record_json": "text",
      "record_sha256": "text",
      "selected_at": "text"
  }, required: false },
  { manifest: "heads", table: "computer_agent_preferred_dispatch_settlement", order_by: "selection_id", columns: {
      "selection_id": "text",
      "dispatch_id": "text",
      "record_json": "text",
      "record_sha256": "text",
      "settled_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_model_spend_admission", order_by: "operation_id, stage_index", columns: {
      "authorization_ref": "text",
      "operation_id": "text",
      "workflow_operation_id": "text",
      "stage_index": "int",
      "stage_attempt_ref": "text",
      "stage_request_sha256": "text",
      "stage_request_json": "text",
      "workflow_budget_receipt_ref": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "intent_json": "text",
      "reservation_id": "text",
      "quote_ref": "text",
      "quote_json": "text",
      "authority_json": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "deployment_generation": "text",
      "policy_decision_ref": "text",
      "policy_generation": "text",
      "currentness_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "workflow_authorization_receipt_ref": "text",
      "route_ref": "text",
      "expected_deployment_json": "text",
      "approval_json": "text",
      "admission_revision": "int",
      "admission_sha256": "text",
      "decision_digest": "text",
      "max_input_bytes": "int",
      "max_output_bytes": "int",
      "expires_at": "text",
      "created_at": "text",
      "role": "text-or-null"
  }, required: false },
  { manifest: "generations", table: "research_semantic_config_revision", order_by: "revision_ref", columns: {
      "revision_ref": "text",
      "config_sha256": "text",
      "config_json": "text",
      "byte_length": "int",
      "protocol": "text",
      "created_at": "text",
      "created_by_principal_ref": "text"
  }, required: false },
  { manifest: "purge", table: "operation_intent", order_by: "intent_id, revision", columns: {
      "intent_id": "text",
      "revision": "int",
      "operation_kind": "text",
      "principal_ref": "text",
      "idempotency_key": "text",
      "payload_ref": "text",
      "policy_decision_ref": "text",
      "budget_reservation_ref": "text-or-null",
      "cancellation_ref": "text-or-null",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "operation_attempt", order_by: "attempt_id", columns: {
      "attempt_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "attempt_number": "int",
      "state": "text",
      "checkpoint_ref": "text-or-null",
      "error_code": "text-or-null",
      "started_at": "text",
      "ended_at": "text-or-null"
  }, required: false },
  { manifest: "purge", table: "operation_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "intent_id": "text",
      "intent_revision": "int",
      "attempt_id": "text",
      "outcome": "text",
      "output_refs_json": "text",
      "readback_receipt_refs_json": "text",
      "reconciliation_required": "int",
      "reason_codes_json": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "outbox", order_by: "outbox_id", columns: {
      "outbox_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "topic": "text",
      "payload_ref": "text",
      "state": "text",
      "attempts": "int",
      "next_attempt_at": "int",
      "lease_owner": "text-or-null",
      "lease_until": "int-or-null",
      "queue_message_id": "text-or-null",
      "last_error_code": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "payload_sha256": "text-or-null",
      "lease_generation": "int"
  }, required: false },
  { manifest: "purge", table: "job", order_by: "job_id", columns: {
      "job_id": "text",
      "intent_id": "text",
      "intent_revision": "int",
      "state": "text",
      "current_stage": "text-or-null",
      "progress_cursor": "text-or-null",
      "workflow_instance_id": "text-or-null",
      "terminal_receipt_ref": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "delivery_inbox", order_by: "message_id", columns: {
      "message_id": "text",
      "idempotency_key": "text",
      "topic": "text",
      "payload_ref": "text",
      "state": "text",
      "attempt": "int",
      "lease_owner": "text-or-null",
      "lease_generation": "int",
      "lease_until": "int-or-null",
      "result_receipt_ref": "text-or-null",
      "last_error_code": "text-or-null",
      "first_seen_at": "int",
      "updated_at": "int",
      "payload_sha256": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "investigation_event", order_by: "investigation_id, sequence", columns: {
      "investigation_id": "text",
      "sequence": "int",
      "event_id": "text",
      "kind": "text",
      "payload_ref": "text",
      "actor_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "investigation_checkpoint", order_by: "investigation_id, investigation_revision, stage, checkpoint_ref", columns: {
      "investigation_id": "text",
      "investigation_revision": "int",
      "stage": "text",
      "checkpoint_ref": "text",
      "input_manifest_ref": "text",
      "output_manifest_ref": "text",
      "idempotency_key": "text",
      "budget_receipt_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "evidence_freeze", order_by: "freeze_id, revision", columns: {
      "freeze_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "investigation_revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "coverage_denominator_ref": "text",
      "contract_protocol_digest": "text",
      "lane_digest": "text",
      "manifest_r2_key": "text",
      "frozen_at": "text",
      "superseded_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "claim_audit", order_by: "audit_id, revision", columns: {
      "audit_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "investigation_revision": "int",
      "evidence_freeze_id": "text",
      "evidence_freeze_revision": "int",
      "manifest_r2_key": "text",
      "material_claim_count": "int",
      "failed_claim_count": "int",
      "unresolved_precision_count": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "coverage_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "investigation_revision": "int",
      "denominator_kind": "text",
      "eligible_count": "int",
      "represented_count": "int",
      "cited_count": "int",
      "terminal_disposition": "text",
      "manifest_r2_key": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "research_debt", order_by: "debt_id, revision", columns: {
      "debt_id": "text",
      "revision": "int",
      "investigation_id": "text",
      "kind": "text",
      "blocking_effect": "text",
      "next_probe": "text",
      "owner_ref": "text",
      "status": "text",
      "manifest_r2_key": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "budget_reservation", order_by: "reservation_id", columns: {
      "reservation_id": "text",
      "operation_kind": "text",
      "project_id": "text-or-null",
      "platform_usd": "real",
      "workers_ai_usd": "real",
      "byok_usd": "real",
      "max_total_usd": "real",
      "workflow_steps": "int",
      "state": "text",
      "expires_at": "text",
      "created_at": "text",
      "principal_ref": "text-or-null",
      "idempotency_key": "text-or-null",
      "request_sha256": "text-or-null",
      "request_json": "text-or-null",
      "policy_decision_ref": "text-or-null",
      "credential_generation": "text-or-null",
      "deployment_generation": "text-or-null",
      "quote_ref": "text-or-null",
      "expected_sources": "int-or-null",
      "expected_sections": "int-or-null",
      "confidence": "real-or-null",
      "quote_json": "text-or-null",
      "authority_json": "text-or-null",
      "stage_attempt_ref": "text-or-null",
      "stage_request_sha256": "text-or-null"
  }, required: false },
  { manifest: "purge", table: "erasure_case", order_by: "erasure_id, revision", columns: {
      "erasure_id": "text",
      "revision": "int",
      "state": "text",
      "exact_subject_refs_json": "text",
      "requested_locations_json": "text",
      "completed_locations_json": "text",
      "blocked_locations_json": "text",
      "legal_basis_ref": "text",
      "deadline": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_execution", order_by: "erasure_id, revision", columns: {
      "erasure_id": "text",
      "revision": "int",
      "request_json": "text",
      "request_sha256": "text",
      "state": "text",
      "lease_owner": "text-or-null",
      "lease_generation": "int",
      "lease_until": "int-or-null",
      "closure_digest": "text-or-null",
      "terminal_receipt_json": "text-or-null",
      "terminal_receipt_sha256": "text-or-null",
      "purge_ledger_revision": "int-or-null",
      "last_error_code": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
];
