import type { TableSpec } from "./coherent-cut.js";

// Canonical publication and COW authority introduced by migrations 0098/0100.
// Preserve these histories during recovery to prevent duplicate acceptance or paid effects.
export const DURABLE_CORE_TABLE_SPECS_E: readonly TableSpec[] = [
  { manifest: "heads", table: "artifact_publication_receipt", order_by: "publication_ref", columns: {
    "publication_ref": "text",
    "artifact_id": "text",
    "draft_revision": "int",
    "intent_id": "text",
    "intent_revision": "int",
    "attempt_id": "text",
    "operation_receipt_id": "text",
    "operation_receipt_revision": "int",
    "outbox_id": "text",
    "principal_ref": "text",
    "idempotency_key": "text",
    "authorization_scope_id": "text",
    "authorization_scope_revision": "int",
    "authorization_receipt_ref": "text",
    "policy_authority_ref": "text",
    "acceptance_decision_ref": "text",
    "acceptance_provenance_ref": "text",
    "acceptance_decision_json": "text",
    "acceptance_decision_sha256": "text",
    "credential_generation": "text",
    "authorization_expires_at": "text",
    "deployment_generation": "text",
    "expected_publication_revision": "int-or-null",
    "publication_revision": "int",
    "expected_draft_head_revision": "int",
    "manifest_sha256": "text",
    "verification_set_json": "text",
    "verification_set_sha256": "text",
    "evidence_currentness_json": "text",
    "evidence_currentness_sha256": "text",
    "purge_ledger_revision": "int",
    "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_publication_head", order_by: "artifact_id", columns: {
    "artifact_id": "text",
    "publication_revision": "int",
    "draft_revision": "int",
    "publication_ref": "text",
    "disposition": "text",
    "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_section_revise_run", order_by: "operation_id", columns: {
    "operation_id": "text",
    "protocol": "text",
    "report_intent_id": "text",
    "report_intent_revision": "int",
    "artifact_id": "text",
    "parent_revision": "int",
    "section_contract_id": "text",
    "principal_ref": "text",
    "credential_generation": "text",
    "deployment_generation": "text",
    "policy_generation": "text",
    "policy_authority_ref": "text",
    "authorization_receipt_ref": "text",
    "scope_snapshot_id": "text",
    "scope_snapshot_revision": "int",
    "purge_revision": "int",
    "idempotency_key": "text",
    "handler_generation": "text",
    "request_json": "text",
    "request_sha256": "text",
    "run_revision": "int",
    "state": "text",
    "current_attempt_ref": "text-or-null",
    "created_at": "text",
    "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_section_revise_attempt", order_by: "operation_id, attempt_number", columns: {
    "operation_id": "text",
    "attempt_number": "int",
    "expected_run_revision": "int",
    "attempt_ref": "text",
    "request_json": "text",
    "request_sha256": "text",
    "budget_receipt_ref": "text",
    "budget_expires_at_ms": "int",
    "budget_max_total_usd": "real",
    "state": "text",
    "output_json": "text-or-null",
    "created_at": "text",
    "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_section_revise_spend_admission", order_by: "authorization_ref", columns: {
    "authorization_ref": "text",
    "operation_id": "text",
    "call_slot": "text",
    "workflow_operation_id": "text",
    "stage_attempt_ref": "text",
    "stage_request_sha256": "text",
    "workflow_budget_receipt_ref": "text",
    "stage_request_json": "text",
    "intent_id": "text",
    "intent_revision": "int",
    "intent_json": "text",
    "reservation_id": "text",
    "quote_ref": "text",
    "quote_json": "text",
    "authority_json": "text",
    "principal_ref": "text",
    "client_class": "text",
    "credential_generation": "text",
    "deployment_generation": "text",
    "policy_decision_ref": "text",
    "policy_generation": "text",
    "currentness_digest": "text",
    "scope_snapshot_id": "text",
    "scope_snapshot_revision": "int",
    "workflow_authorization_receipt_ref": "text",
    "route_ref": "text",
    "expected_deployment_json": "text",
    "approval_json": "text",
    "admission_revision": "int",
    "admission_sha256": "text",
    "decision_digest": "text",
    "request_json": "text",
    "max_input_bytes": "int",
    "max_output_bytes": "int",
    "expires_at": "text",
    "created_at": "text"
  }, required: false },
];
