import type { TableSpec } from "./coherent-cut.js";

// Explicit PRAGMA-derived columns and deterministic primary-key ordering.
export const DURABLE_CORE_TABLE_SPECS_D: readonly TableSpec[] = [
  { manifest: "purge", table: "erasure_dependency_registry", order_by: "dependency_id", columns: {
      "dependency_id": "text",
      "exact_subject_ref": "text",
      "location": "text",
      "canonical_ref": "text",
      "provider_ref": "text-or-null",
      "object_identity_digest": "text",
      "shared_reference_key": "text-or-null",
      "retention_or_hold_ref": "text-or-null",
      "next_review_at": "text-or-null",
      "declassification_receipt_ref": "text-or-null",
      "state": "text",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_target", order_by: "erasure_id, erasure_revision, target_id", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "target_id": "text",
      "target_kind": "text",
      "exact_subject_ref": "text",
      "location": "text",
      "canonical_ref": "text",
      "provider_ref": "text-or-null",
      "identity_digest": "text",
      "shared_live_reference_count": "int",
      "retention_or_hold_ref": "text-or-null",
      "next_review_at": "text-or-null",
      "state": "text",
      "delete_receipt_ref": "text-or-null",
      "absence_receipt_ref": "text-or-null",
      "last_error_code": "text-or-null",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_stage_receipt", order_by: "erasure_id, erasure_revision, stage", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "stage": "text",
      "lease_generation": "int",
      "receipt_ref": "text",
      "payload_digest": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_dependent_invalidation", order_by: "erasure_id, erasure_revision, dependent_ref", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "dependent_ref": "text",
      "dependent_kind": "text",
      "disposition": "text",
      "receipt_ref": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_terminal_guard", order_by: "erasure_id, erasure_revision", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "closure_digest": "text",
      "requested_locations_json": "text",
      "completed_locations_json": "text",
      "blocked_locations_json": "text",
      "terminal_state": "text",
      "receipt_sha256": "text",
      "purge_ledger_revision": "int",
      "verified": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "purge", table: "backup_purge_obligation", order_by: "erasure_id, erasure_revision, backup_epoch_id", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "backup_epoch_id": "text",
      "target_id": "text",
      "state": "text",
      "policy_or_hold_ref": "text-or-null",
      "next_review_at": "text-or-null",
      "delete_receipt_ref": "text-or-null",
      "absence_receipt_ref": "text-or-null",
      "updated_at": "text"
  }, required: false },
  { manifest: "purge", table: "erasure_admission_request", order_by: "erasure_id, erasure_revision", columns: {
      "erasure_id": "text",
      "erasure_revision": "int",
      "permission_ref": "text",
      "permission_revision": "int",
      "principal_ref": "text",
      "credential_generation": "text",
      "permission_sha256": "text",
      "request_json": "text",
      "request_sha256": "text",
      "request_identity_sha256": "text",
      "admitted_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "federation_reference_manifest", order_by: "manifest_id, revision", columns: {
      "manifest_id": "text",
      "revision": "int",
      "manifest_json": "text",
      "manifest_digest": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "client_fence_ref": "text-or-null",
      "expires_at": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "federation_job", order_by: "job_id", columns: {
      "job_id": "text",
      "exchange_id": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "request_json": "text",
      "requester_principal_ref": "text",
      "requester_credential_generation": "text",
      "server_principal_ref": "text",
      "server_credential_generation": "text",
      "bridge_generation": "text",
      "client_fence_ref": "text",
      "allowed_manifest_id": "text",
      "allowed_manifest_revision": "int",
      "origin_trace_id": "text",
      "attempt": "int",
      "transport_state": "text",
      "status_json": "text",
      "observed_completion_disposition": "text-or-null",
      "result_json": "text-or-null",
      "cancellation_reason": "text-or-null",
      "cancelled_at": "text-or-null",
      "created_at": "text",
      "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "navigation_artifact", order_by: "scope_snapshot_id, scope_snapshot_revision, artifact_kind, subject_id, subject_revision", columns: {
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "artifact_kind": "text",
      "subject_id": "text",
      "subject_revision": "int",
      "artifact_id": "text",
      "artifact_revision": "int",
      "body_digest": "text",
      "body_json": "text",
      "source_bindings_json": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "bundle_ingest_operation", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "origin_authentication_receipt_ref": "text",
      "idempotency_key": "text",
      "input_fingerprint": "text",
      "manifest_sha256": "text",
      "manifest_json": "text",
      "file_hashes_json": "text",
      "total_bytes": "int",
      "source_namespace_id": "text",
      "owner_system_id": "text",
      "source_owner_generation": "text",
      "source_revision_ref": "text",
      "source_id": "text",
      "expected_head_revision_ref": "text-or-null",
      "residency_key_json": "text",
      "residency_key_digest": "text",
      "policy_revision": "int",
      "policy_snapshot_json": "text",
      "policy_snapshot_sha256": "text",
      "candidate_id": "text",
      "staging_session_ref": "text-or-null",
      "qualification_report_ref": "text-or-null",
      "decision_receipt_ref": "text-or-null",
      "promotion_receipt_ref": "text-or-null",
      "state": "text",
      "bundle_receipt_json": "text-or-null",
      "bundle_receipt_sha256": "text-or-null",
      "created_at": "text",
      "updated_at": "text",
      "expires_at": "text",
      "client_origin_json": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "bundle_ingest_commit_guard", order_by: "operation_id", columns: {
      "operation_id": "text",
      "source_revision_ref": "text",
      "ingest_receipt_id": "text",
      "ingest_receipt_revision": "int",
      "projection_intent_id": "text",
      "projection_intent_revision": "int",
      "outbox_id": "text",
      "verified": "int",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "source_acquisition_candidate", order_by: "candidate_id, revision", columns: {
      "candidate_id": "text",
      "revision": "int",
      "operation_id": "text",
      "observed_locator_identifier_or_upload_ref": "text",
      "proposer_principal_ref": "text",
      "proposer_run_ref": "text-or-null",
      "allowed_reference_manifest_id": "text-or-null",
      "allowed_reference_manifest_revision": "int-or-null",
      "proposed_source_class": "text",
      "purpose": "text",
      "requested_scope_expression_json": "text",
      "untrusted_metadata_json": "text",
      "staging_object_ref": "text-or-null",
      "policy_refs_json": "text",
      "state": "text",
      "effect_ceiling": "text",
      "created_at": "text",
      "expires_at": "text",
      "terminal_receipt_ref": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "qualification_report", order_by: "report_id, revision", columns: {
      "report_id": "text",
      "revision": "int",
      "operation_id": "text",
      "source_revision_ref": "text",
      "parser_profile_generation": "text",
      "checks_json": "text",
      "overall": "text",
      "exact_precision_ceiling": "text",
      "warnings_json": "text",
      "report_json": "text",
      "report_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "source_admission_decision", order_by: "decision_receipt_ref", columns: {
      "decision_receipt_ref": "text",
      "operation_id": "text",
      "source_namespace_id": "text",
      "owner_system_id": "text",
      "source_owner_generation": "text",
      "source_revision_ref": "text",
      "origin_authentication_receipt_ref": "text",
      "source_class": "text",
      "assurance_ceiling": "text",
      "instruction_taint": "text",
      "allowed_effects": "text",
      "object_residency_key_digest": "text",
      "allowed_use_json": "text",
      "disclosure_ceiling": "text",
      "license_policy_ref": "text",
      "expires_at": "text-or-null",
      "decision": "text",
      "reason_codes_json": "text",
      "decision_json": "text",
      "decision_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "sources", table: "drive_observation", order_by: "generation_id, object_kind, object_id, content_sha256", columns: {
      "generation_id": "text",
      "object_kind": "text",
      "object_id": "text",
      "idempotency_key": "text-or-null",
      "content_sha256": "text",
      "observed_row": "int",
      "drive_modified_time": "text",
      "actor_claim": "text-or-null",
      "frozen_r2_key": "text",
      "disposition": "text",
      "imported_at": "text"
  }, required: false },
  { manifest: "heads", table: "incident", order_by: "incident_id", columns: {
      "incident_id": "text",
      "severity": "text",
      "kind": "text",
      "state": "text",
      "details_ref": "text",
      "created_at": "text",
      "resolved_at": "text-or-null"
  }, required: false },
  { manifest: "heads", table: "evidence_resolution_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "handle_id": "text",
      "handle_revision": "int",
      "source_revision_ref": "text",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "authorization_receipt_ref": "text",
      "normalized_object_ref": "text",
      "normalized_object_ref_digest": "text",
      "source_revision_content_sha256": "text",
      "source_object_size": "int",
      "scope_snapshot_digest": "text",
      "anchor_digest": "text",
      "excerpt_sha256": "text",
      "excerpt_byte_length": "int",
      "source_owner_generation": "text",
      "purge_state": "text",
      "terminal_state": "text",
      "receipt_json": "text",
      "receipt_sha256": "text",
      "resolved_at": "text"
  }, required: false },
  { manifest: "heads", table: "citation_resolution_receipt", order_by: "receipt_id, revision", columns: {
      "receipt_id": "text",
      "revision": "int",
      "scope_snapshot_id": "text",
      "scope_snapshot_revision": "int",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "authorization_receipt_ref": "text",
      "requested_handle_refs_json": "text",
      "resolved_json": "text",
      "rejected_json": "text",
      "requested_count": "int",
      "resolved_count": "int",
      "all_material_citations_resolved": "int",
      "receipt_json": "text",
      "receipt_sha256": "text",
      "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "orientation_request", order_by: "operation_id", columns: {
      "operation_id": "text",
      "principal_ref": "text",
      "client_class": "text",
      "credential_generation": "text",
      "idempotency_key": "text",
      "request_digest": "text",
      "state": "text",
      "snapshot_id": "text-or-null",
      "snapshot_revision": "int-or-null",
      "result_json": "text-or-null",
      "result_digest": "text-or-null",
      "created_at": "text",
      "expires_at": "text",
      "execution_operation_id": "text-or-null",
      "execution_client_grant_id": "text-or-null",
      "execution_client_grant_revision": "int-or-null"
  }, required: false },
  { manifest: "heads", table: "orientation_authority_epoch", order_by: "singleton", columns: {
      "singleton": "int",
      "generation": "int"
  }, required: false },
  { manifest: "heads", table: "google_oauth_intent_receipt", order_by: "intent_id", columns: {
      "intent_id": "text",
      "operation_ref": "text",
      "principal_id": "text",
      "configuration_json": "text",
      "state_sha256": "text",
      "terminal_state": "text",
      "terminal_at": "text",
      "retained_at": "text"
  }, required: false },
];
