import type { TableSpec } from "./backup-table-spec-types.js";

// Canonical publication and COW authority introduced by migrations 0098/0100.
// Preserve these histories during recovery to prevent duplicate acceptance or paid effects.
export const DURABLE_CORE_TABLE_SPECS_E: readonly TableSpec[] = [
  { manifest: "heads", table: "research_run_configuration", order_by: "operation_id", columns: {
    "operation_id": "text",
    "investigation_id": "text",
    "principal_ref": "text",
    "deployment_generation": "text",
    "protocol": "text",
    "mode": "text",
    "configuration_ref": "text",
    "configuration_sha256": "text",
    "configuration_json": "text",
    "byte_length": "int",
    "created_at": "text"
  }, required: false },
  { manifest: "projects", table: "research_project_model_configuration_revision", order_by: "owner_id, project_id, configuration_ref", columns: {
    "owner_id": "text",
    "project_id": "text",
    "configuration_ref": "text",
    "configuration_sha256": "text",
    "configuration_json": "text",
    "byte_length": "int",
    "protocol": "text",
    "created_at": "text",
    "created_by_principal_ref": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_publication_receipt", order_by: "publication_ref", columns: {
    "publication_ref": "text",
    "artifact_id": "text",
    "draft_revision": "int",
    "intent_id": "text",
    "intent_revision": "int",
    "attempt_id": "text",
    "operation_receipt_id": "text",
    "operation_receipt_revision": "int",
    "outbox_id": "text",
    "principal_ref": "text",
    "idempotency_key": "text",
    "authorization_scope_id": "text",
    "authorization_scope_revision": "int",
    "authorization_receipt_ref": "text",
    "policy_authority_ref": "text",
    "acceptance_decision_ref": "text",
    "acceptance_provenance_ref": "text",
    "acceptance_decision_json": "text",
    "acceptance_decision_sha256": "text",
    "credential_generation": "text",
    "authorization_expires_at": "text",
    "deployment_generation": "text",
    "expected_publication_revision": "int-or-null",
    "publication_revision": "int",
    "expected_draft_head_revision": "int",
    "manifest_sha256": "text",
    "verification_set_json": "text",
    "verification_set_sha256": "text",
    "evidence_currentness_json": "text",
    "evidence_currentness_sha256": "text",
    "purge_ledger_revision": "int",
    "created_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_publication_head", order_by: "artifact_id", columns: {
    "artifact_id": "text",
    "publication_revision": "int",
    "draft_revision": "int",
    "publication_ref": "text",
    "disposition": "text",
    "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_section_revise_run", order_by: "operation_id", columns: {
    "operation_id": "text",
    "protocol": "text",
    "report_intent_id": "text",
    "report_intent_revision": "int",
    "artifact_id": "text",
    "parent_revision": "int",
    "section_contract_id": "text",
    "principal_ref": "text",
    "credential_generation": "text",
    "deployment_generation": "text",
    "policy_generation": "text",
    "policy_authority_ref": "text",
    "authorization_receipt_ref": "text",
    "scope_snapshot_id": "text",
    "scope_snapshot_revision": "int",
    "purge_revision": "int",
    "idempotency_key": "text",
    "handler_generation": "text",
    "request_json": "text",
    "request_sha256": "text",
    "run_revision": "int",
    "state": "text",
    "current_attempt_ref": "text-or-null",
    "created_at": "text",
    "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_section_revise_attempt", order_by: "operation_id, attempt_number", columns: {
    "operation_id": "text",
    "attempt_number": "int",
    "expected_run_revision": "int",
    "attempt_ref": "text",
    "request_json": "text",
    "request_sha256": "text",
    "budget_receipt_ref": "text",
    "budget_expires_at_ms": "int",
    "budget_max_total_usd": "real",
    "state": "text",
    "output_json": "text-or-null",
    "created_at": "text",
    "updated_at": "text"
  }, required: false },
  { manifest: "heads", table: "artifact_section_revise_spend_admission", order_by: "authorization_ref", columns: {
    "authorization_ref": "text",
    "operation_id": "text",
    "call_slot": "text",
    "workflow_operation_id": "text",
    "stage_attempt_ref": "text",
    "stage_request_sha256": "text",
    "workflow_budget_receipt_ref": "text",
    "stage_request_json": "text",
    "intent_id": "text",
    "intent_revision": "int",
    "intent_json": "text",
    "reservation_id": "text",
    "quote_ref": "text",
    "quote_json": "text",
    "authority_json": "text",
    "principal_ref": "text",
    "client_class": "text",
    "credential_generation": "text",
    "deployment_generation": "text",
    "policy_decision_ref": "text",
    "policy_generation": "text",
    "currentness_digest": "text",
    "scope_snapshot_id": "text",
    "scope_snapshot_revision": "int",
    "workflow_authorization_receipt_ref": "text",
    "route_ref": "text",
    "expected_deployment_json": "text",
    "approval_json": "text",
    "admission_revision": "int",
    "admission_sha256": "text",
    "decision_digest": "text",
    "request_json": "text",
    "max_input_bytes": "int",
    "max_output_bytes": "int",
    "expires_at": "text",
    "created_at": "text"
  }, required: false },
  // Immutable scope-policy facts are exported as historical provenance. The
  // live scope_read_policy authority remains excluded from portable backup.
  { manifest: "scopes", table: "scope_read_policy_lease_refresh_receipt", order_by: "receipt_sequence", columns: {
    "receipt_sequence": "int",
    "refresh_id": "text",
    "source_namespace_id": "text",
    "principal_ref": "text",
    "client_class": "text",
    "credential_generation": "text",
    "access_expires_at": "text",
    "owner_incarnation_ref": "text",
    "source_owner_generation": "text",
    "ownership_record_revision": "int",
    "source_admission_policy_revision": "int",
    "policy_ref": "text",
    "old_generation": "int",
    "new_generation": "int",
    "old_allowed_use_json": "text",
    "old_disclosure_ceiling": "text",
    "old_created_at": "text",
    "old_expires_at": "text",
    "new_expires_at": "text",
    "created_at": "text",
    "state": "text"
  }, required: false },
  { manifest: "scopes", table: "scope_read_policy_history_event", order_by: "history_event_sequence", columns: {
    "history_event_sequence": "int",
    "source_namespace_id": "text",
    "principal_ref": "text",
    "client_class": "text",
    "event_kind": "text",
    "receipt_sequence": "int-or-null",
    "refresh_id": "text-or-null",
    "old_policy_ref": "text-or-null",
    "old_generation": "int-or-null",
    "old_allowed_use_json": "text-or-null",
    "old_disclosure_ceiling": "text-or-null",
    "old_state": "text-or-null",
    "old_expires_at": "text-or-null",
    "old_created_at": "text-or-null",
    "new_policy_ref": "text-or-null",
    "new_generation": "int-or-null",
    "new_allowed_use_json": "text-or-null",
    "new_disclosure_ceiling": "text-or-null",
    "new_state": "text-or-null",
    "new_expires_at": "text-or-null",
    "new_created_at": "text-or-null",
    "created_at": "text"
  }, required: false },
  { manifest: "scopes", table: "scope_read_policy_identity", order_by: "source_namespace_id, principal_ref, client_class", columns: {
    "source_namespace_id": "text",
    "principal_ref": "text",
    "client_class": "text",
    "birth_sequence": "int",
    "last_event_sequence": "int",
    "semantic_sequence": "int"
  }, required: false },
  { manifest: "scopes", table: "scope_read_policy_snapshot_baseline", order_by: "snapshot_id, snapshot_revision", columns: {
    "snapshot_id": "text",
    "snapshot_revision": "int",
    "history_event_sequence_floor": "int",
    "receipt_sequence_floor": "int",
    "pre_migration_semantic": "int"
  }, required: false },
  { manifest: "retention", table: "backup_restore_intent", order_by: "restore_id", columns: {
    "restore_id": "text", "principal_ref": "text", "idempotency_key": "text", "intent_id": "text",
    "intent_revision": "int", "intent_digest": "text", "epoch_id": "text", "offsite_copy_ref": "text",
    "target_binding_json": "text", "state": "text", "created_at": "text", "updated_at": "text"
  }, required: false },
  { manifest: "retention", table: "backup_restore_attempt", order_by: "restore_id, attempt_number", columns: {
    "restore_id": "text", "attempt_number": "int", "attempt_id": "text", "state": "text", "attempt_json": "text",
    "started_at": "text", "ended_at": "text-or-null", "error_code": "text-or-null", "readback_digest": "text-or-null"
  }, required: false },
  { manifest: "retention", table: "backup_restore_receipt", order_by: "restore_id", columns: {
    "restore_id": "text", "attempt_number": "int", "receipt_json": "text", "receipt_digest": "text", "created_at": "text"
  }, required: false },
];
