-- Align the persisted failure-code allowlists with WORKFLOW_FAILURE_CODES.
-- Existing JSON shape, size, phase, stage, privacy, and transition guards are retained.

DROP TRIGGER IF EXISTS research_workflow_first_failure_json_shape;
CREATE TRIGGER research_workflow_first_failure_json_shape BEFORE UPDATE OF first_failure_json ON research_workflow_run
WHEN NEW.first_failure_json IS NOT NULL
BEGIN
 SELECT (CASE WHEN COALESCE((json_valid(NEW.first_failure_json) AND length(CAST(NEW.first_failure_json AS BLOB))<=1024
 AND json_type(NEW.first_failure_json)='object'
 AND json_extract(NEW.first_failure_json,'$.code') IN (
   'WORKFLOW_INPUT_INVALID',
   'WORKFLOW_CONFLICT',
   'WORKFLOW_AUTHORITY_STALE',
   'WORKFLOW_STAGE_OUT_OF_ORDER',
   'WORKFLOW_CANCELLED',
   'WORKFLOW_BUDGET_STOP',
   'WORKFLOW_EFFECT_UNCERTAIN',
   'WORKFLOW_OUTPUT_UNAVAILABLE',
   'WORKFLOW_OUTPUT_CORRUPT',
   'WORKFLOW_CONFIGURATION_MISSING',
   'WORKFLOW_CONFIGURATION_INVALID',
   'WORKFLOW_CREDENTIALS_MISSING',
   'WORKFLOW_CREDENTIALS_INVALID',
   'WORKFLOW_STORAGE_UNAVAILABLE',
   'WORKFLOW_QUALIFICATION_STALE',
   'WORKFLOW_PREPARATION_FAILED',
   'RESEARCH_QUALIFICATION_RENEWAL_READ_TOKEN_REQUIRED',
   'RESEARCH_QUALIFICATION_RENEWAL_AUTHORITY_STALE',
   'RESEARCH_QUALIFICATION_RENEWAL_UNAVAILABLE',
   'RESEARCH_QUALIFICATION_RENEWAL_ROUTE_UNAVAILABLE',
   'MODEL_ATTEMPT_INPUT_INVALID',
   'MODEL_ATTEMPT_AUTHORITY_STALE',
   'MODEL_ATTEMPT_IDENTITY_CONFLICT',
   'MODEL_ATTEMPT_BUDGET_EXPIRED',
   'MODEL_ATTEMPT_CONFLICT',
   'MODEL_ATTEMPT_SETTLEMENT_UNCERTAIN',
   'MODEL_ATTEMPT_READBACK_CORRUPT',
   'MODEL_GATEWAY_DEPLOYMENT_MISSING',
   'MODEL_GATEWAY_PROMPT_COMPILE_FAILED',
   'MODEL_GATEWAY_REQUEST_INVALID',
   'MODEL_GATEWAY_CREDENTIAL_INVALID',
   'MODEL_GATEWAY_TRANSPORT_FAILED',
   'MODEL_GATEWAY_AUTH_REJECTED',
   'MODEL_GATEWAY_LIMIT_REJECTED',
   'MODEL_GATEWAY_POLICY_REJECTED',
   'MODEL_GATEWAY_UPSTREAM_REJECTED',
   'MODEL_GATEWAY_RESPONSE_INVALID',
   'MODEL_GATEWAY_OUTPUT_TRUNCATED',
   'MODEL_GATEWAY_OUTPUT_PERSIST_FAILED',
   'MODEL_GATEWAY_FINGERPRINT_PERSIST_FAILED',
   'MODEL_GATEWAY_PRICING_FAILED',
   'MODEL_PROFILE_BINDING_INPUT_INVALID',
   'MODEL_PROFILE_BINDING_CONFIG_MISSING',
   'MODEL_PROFILE_BINDING_CONFIG_INVALID',
   'MODEL_PROFILE_BINDING_AUTHORITY_STALE',
   'MODEL_PROFILE_BINDING_DEPLOYMENT_MISSING',
   'MODEL_PROFILE_BINDING_DEPLOYMENT_MISMATCH',
   'MODEL_PROFILE_BINDING_EXPIRED',
   'REFERENCE_MANIFEST_INPUT_INVALID',
   'REFERENCE_MANIFEST_SCOPE_STALE',
   'REFERENCE_MANIFEST_EVIDENCE_INVALID',
   'REFERENCE_MANIFEST_POLICY_INVALID',
   'REFERENCE_MANIFEST_PERSISTENCE_UNCERTAIN',
   'EVIDENCE_INPUT_INVALID',
   'EVIDENCE_SCOPE_NOT_FOUND',
   'EVIDENCE_SCOPE_INVALIDATED',
   'EVIDENCE_SCOPE_EXPIRED',
   'EVIDENCE_AUTHORIZATION_DENIED',
   'EVIDENCE_SOURCE_NOT_FOUND',
   'EVIDENCE_SOURCE_NOT_LIVE',
   'EVIDENCE_OWNER_GENERATION_MISMATCH',
   'EVIDENCE_SCOPE_MISMATCH',
   'EVIDENCE_LOCATOR_NOT_RESOLVABLE',
   'EVIDENCE_PRECISION_UNSUPPORTED',
   'EVIDENCE_OBJECT_NOT_FOUND',
   'EVIDENCE_OBJECT_INTEGRITY',
   'EVIDENCE_RANGE_INVALID',
   'EVIDENCE_HANDLE_NOT_FOUND',
   'EVIDENCE_HANDLE_NOT_LIVE',
   'EVIDENCE_IDENTITY_CONFLICT',
   'EVIDENCE_SETTLEMENT_UNCERTAIN',
   'CITATION_SET_INVALID'
 )
 AND json_extract(NEW.first_failure_json,'$.phase') IN ('PREPARATION','STAGE','RECOVERY')
 AND json_type(NEW.first_failure_json,'$.retryable') IN ('true','false')
 AND (json_extract(NEW.first_failure_json,'$.phase')='PREPARATION' AND json_type(NEW.first_failure_json,'$.stage') IS NULL
   OR json_extract(NEW.first_failure_json,'$.phase') IN ('STAGE','RECOVERY') AND json_extract(NEW.first_failure_json,'$.stage') IN (
   'FREEZE_PROTOCOL_AND_SCOPE',
   'ORIENT',
   'INTERPRET',
   'COMPILE_OBLIGATIONS',
   'PLAN',
   'RETRIEVE_BRANCHES',
   'ACQUIRE_AND_CAPTURE',
   'READ_AND_EXTRACT',
   'ANALYZE_BRANCHES',
   'COUNTER_SEARCH',
   'RECONCILE',
   'FREEZE_EVIDENCE',
   'SYNTHESIZE',
   'VERIFY',
   'AUDIT_CLAIMS',
   'RESOLVE_CITATIONS',
   'CALCULATE_COVERAGE',
   'MATERIALIZE'
 ))
 AND (json_extract(NEW.first_failure_json,'$.retryable')=0 OR
   json_extract(NEW.first_failure_json,'$.phase')='PREPARATION' AND json_extract(NEW.first_failure_json,'$.code')='WORKFLOW_STORAGE_UNAVAILABLE')),0)<>1 THEN RAISE(ABORT,'WORKFLOW_CONFLICT') END);
 SELECT (CASE WHEN EXISTS (SELECT 1 FROM json_each(NEW.first_failure_json) WHERE key NOT IN ('code','phase','stage','retryable'))
   OR (SELECT COUNT(*) FROM json_each(NEW.first_failure_json)) <> (CASE json_extract(NEW.first_failure_json,'$.phase') WHEN 'PREPARATION' THEN 3 ELSE 4 END)
   THEN RAISE(ABORT,'WORKFLOW_CONFLICT') END);
END;

DROP TRIGGER IF EXISTS research_workflow_latest_failure_json_shape;
CREATE TRIGGER research_workflow_latest_failure_json_shape BEFORE UPDATE OF latest_failure_json ON research_workflow_run
WHEN NEW.latest_failure_json IS NOT NULL
BEGIN
 SELECT (CASE WHEN COALESCE((json_valid(NEW.latest_failure_json) AND length(CAST(NEW.latest_failure_json AS BLOB))<=1024
 AND json_type(NEW.latest_failure_json)='object'
 AND json_extract(NEW.latest_failure_json,'$.code') IN (
   'WORKFLOW_INPUT_INVALID',
   'WORKFLOW_CONFLICT',
   'WORKFLOW_AUTHORITY_STALE',
   'WORKFLOW_STAGE_OUT_OF_ORDER',
   'WORKFLOW_CANCELLED',
   'WORKFLOW_BUDGET_STOP',
   'WORKFLOW_EFFECT_UNCERTAIN',
   'WORKFLOW_OUTPUT_UNAVAILABLE',
   'WORKFLOW_OUTPUT_CORRUPT',
   'WORKFLOW_CONFIGURATION_MISSING',
   'WORKFLOW_CONFIGURATION_INVALID',
   'WORKFLOW_CREDENTIALS_MISSING',
   'WORKFLOW_CREDENTIALS_INVALID',
   'WORKFLOW_STORAGE_UNAVAILABLE',
   'WORKFLOW_QUALIFICATION_STALE',
   'WORKFLOW_PREPARATION_FAILED',
   'RESEARCH_QUALIFICATION_RENEWAL_READ_TOKEN_REQUIRED',
   'RESEARCH_QUALIFICATION_RENEWAL_AUTHORITY_STALE',
   'RESEARCH_QUALIFICATION_RENEWAL_UNAVAILABLE',
   'RESEARCH_QUALIFICATION_RENEWAL_ROUTE_UNAVAILABLE',
   'MODEL_ATTEMPT_INPUT_INVALID',
   'MODEL_ATTEMPT_AUTHORITY_STALE',
   'MODEL_ATTEMPT_IDENTITY_CONFLICT',
   'MODEL_ATTEMPT_BUDGET_EXPIRED',
   'MODEL_ATTEMPT_CONFLICT',
   'MODEL_ATTEMPT_SETTLEMENT_UNCERTAIN',
   'MODEL_ATTEMPT_READBACK_CORRUPT',
   'MODEL_GATEWAY_DEPLOYMENT_MISSING',
   'MODEL_GATEWAY_PROMPT_COMPILE_FAILED',
   'MODEL_GATEWAY_REQUEST_INVALID',
   'MODEL_GATEWAY_CREDENTIAL_INVALID',
   'MODEL_GATEWAY_TRANSPORT_FAILED',
   'MODEL_GATEWAY_AUTH_REJECTED',
   'MODEL_GATEWAY_LIMIT_REJECTED',
   'MODEL_GATEWAY_POLICY_REJECTED',
   'MODEL_GATEWAY_UPSTREAM_REJECTED',
   'MODEL_GATEWAY_RESPONSE_INVALID',
   'MODEL_GATEWAY_OUTPUT_TRUNCATED',
   'MODEL_GATEWAY_OUTPUT_PERSIST_FAILED',
   'MODEL_GATEWAY_FINGERPRINT_PERSIST_FAILED',
   'MODEL_GATEWAY_PRICING_FAILED',
   'MODEL_PROFILE_BINDING_INPUT_INVALID',
   'MODEL_PROFILE_BINDING_CONFIG_MISSING',
   'MODEL_PROFILE_BINDING_CONFIG_INVALID',
   'MODEL_PROFILE_BINDING_AUTHORITY_STALE',
   'MODEL_PROFILE_BINDING_DEPLOYMENT_MISSING',
   'MODEL_PROFILE_BINDING_DEPLOYMENT_MISMATCH',
   'MODEL_PROFILE_BINDING_EXPIRED',
   'REFERENCE_MANIFEST_INPUT_INVALID',
   'REFERENCE_MANIFEST_SCOPE_STALE',
   'REFERENCE_MANIFEST_EVIDENCE_INVALID',
   'REFERENCE_MANIFEST_POLICY_INVALID',
   'REFERENCE_MANIFEST_PERSISTENCE_UNCERTAIN',
   'EVIDENCE_INPUT_INVALID',
   'EVIDENCE_SCOPE_NOT_FOUND',
   'EVIDENCE_SCOPE_INVALIDATED',
   'EVIDENCE_SCOPE_EXPIRED',
   'EVIDENCE_AUTHORIZATION_DENIED',
   'EVIDENCE_SOURCE_NOT_FOUND',
   'EVIDENCE_SOURCE_NOT_LIVE',
   'EVIDENCE_OWNER_GENERATION_MISMATCH',
   'EVIDENCE_SCOPE_MISMATCH',
   'EVIDENCE_LOCATOR_NOT_RESOLVABLE',
   'EVIDENCE_PRECISION_UNSUPPORTED',
   'EVIDENCE_OBJECT_NOT_FOUND',
   'EVIDENCE_OBJECT_INTEGRITY',
   'EVIDENCE_RANGE_INVALID',
   'EVIDENCE_HANDLE_NOT_FOUND',
   'EVIDENCE_HANDLE_NOT_LIVE',
   'EVIDENCE_IDENTITY_CONFLICT',
   'EVIDENCE_SETTLEMENT_UNCERTAIN',
   'CITATION_SET_INVALID'
 )
 AND json_extract(NEW.latest_failure_json,'$.phase') IN ('PREPARATION','STAGE','RECOVERY')
 AND json_type(NEW.latest_failure_json,'$.retryable') IN ('true','false')
 AND (json_extract(NEW.latest_failure_json,'$.phase')='PREPARATION' AND json_type(NEW.latest_failure_json,'$.stage') IS NULL
   OR json_extract(NEW.latest_failure_json,'$.phase') IN ('STAGE','RECOVERY') AND json_extract(NEW.latest_failure_json,'$.stage') IN (
   'FREEZE_PROTOCOL_AND_SCOPE',
   'ORIENT',
   'INTERPRET',
   'COMPILE_OBLIGATIONS',
   'PLAN',
   'RETRIEVE_BRANCHES',
   'ACQUIRE_AND_CAPTURE',
   'READ_AND_EXTRACT',
   'ANALYZE_BRANCHES',
   'COUNTER_SEARCH',
   'RECONCILE',
   'FREEZE_EVIDENCE',
   'SYNTHESIZE',
   'VERIFY',
   'AUDIT_CLAIMS',
   'RESOLVE_CITATIONS',
   'CALCULATE_COVERAGE',
   'MATERIALIZE'
 ))
 AND (json_extract(NEW.latest_failure_json,'$.retryable')=0 OR
   json_extract(NEW.latest_failure_json,'$.phase')='PREPARATION' AND json_extract(NEW.latest_failure_json,'$.code')='WORKFLOW_STORAGE_UNAVAILABLE')),0)<>1 THEN RAISE(ABORT,'WORKFLOW_CONFLICT') END);
 SELECT (CASE WHEN EXISTS (SELECT 1 FROM json_each(NEW.latest_failure_json) WHERE key NOT IN ('code','phase','stage','retryable'))
   OR (SELECT COUNT(*) FROM json_each(NEW.latest_failure_json)) <> (CASE json_extract(NEW.latest_failure_json,'$.phase') WHEN 'PREPARATION' THEN 3 ELSE 4 END)
   THEN RAISE(ABORT,'WORKFLOW_CONFLICT') END);
END;

DROP TRIGGER IF EXISTS research_workflow_attempt_failure_shape;
CREATE TRIGGER research_workflow_attempt_failure_shape BEFORE UPDATE OF first_failure_json ON research_workflow_attempt
WHEN NEW.first_failure_json IS NOT NULL
BEGIN
 SELECT (CASE WHEN COALESCE((json_valid(NEW.first_failure_json) AND length(CAST(NEW.first_failure_json AS BLOB))<=1024
 AND json_type(NEW.first_failure_json)='object'
 AND json_extract(NEW.first_failure_json,'$.code') IN (
   'WORKFLOW_INPUT_INVALID',
   'WORKFLOW_CONFLICT',
   'WORKFLOW_AUTHORITY_STALE',
   'WORKFLOW_STAGE_OUT_OF_ORDER',
   'WORKFLOW_CANCELLED',
   'WORKFLOW_BUDGET_STOP',
   'WORKFLOW_EFFECT_UNCERTAIN',
   'WORKFLOW_OUTPUT_UNAVAILABLE',
   'WORKFLOW_OUTPUT_CORRUPT',
   'WORKFLOW_CONFIGURATION_MISSING',
   'WORKFLOW_CONFIGURATION_INVALID',
   'WORKFLOW_CREDENTIALS_MISSING',
   'WORKFLOW_CREDENTIALS_INVALID',
   'WORKFLOW_STORAGE_UNAVAILABLE',
   'WORKFLOW_QUALIFICATION_STALE',
   'WORKFLOW_PREPARATION_FAILED',
   'RESEARCH_QUALIFICATION_RENEWAL_READ_TOKEN_REQUIRED',
   'RESEARCH_QUALIFICATION_RENEWAL_AUTHORITY_STALE',
   'RESEARCH_QUALIFICATION_RENEWAL_UNAVAILABLE',
   'RESEARCH_QUALIFICATION_RENEWAL_ROUTE_UNAVAILABLE',
   'MODEL_ATTEMPT_INPUT_INVALID',
   'MODEL_ATTEMPT_AUTHORITY_STALE',
   'MODEL_ATTEMPT_IDENTITY_CONFLICT',
   'MODEL_ATTEMPT_BUDGET_EXPIRED',
   'MODEL_ATTEMPT_CONFLICT',
   'MODEL_ATTEMPT_SETTLEMENT_UNCERTAIN',
   'MODEL_ATTEMPT_READBACK_CORRUPT',
   'MODEL_GATEWAY_DEPLOYMENT_MISSING',
   'MODEL_GATEWAY_PROMPT_COMPILE_FAILED',
   'MODEL_GATEWAY_REQUEST_INVALID',
   'MODEL_GATEWAY_CREDENTIAL_INVALID',
   'MODEL_GATEWAY_TRANSPORT_FAILED',
   'MODEL_GATEWAY_AUTH_REJECTED',
   'MODEL_GATEWAY_LIMIT_REJECTED',
   'MODEL_GATEWAY_POLICY_REJECTED',
   'MODEL_GATEWAY_UPSTREAM_REJECTED',
   'MODEL_GATEWAY_RESPONSE_INVALID',
   'MODEL_GATEWAY_OUTPUT_TRUNCATED',
   'MODEL_GATEWAY_OUTPUT_PERSIST_FAILED',
   'MODEL_GATEWAY_FINGERPRINT_PERSIST_FAILED',
   'MODEL_GATEWAY_PRICING_FAILED',
   'MODEL_PROFILE_BINDING_INPUT_INVALID',
   'MODEL_PROFILE_BINDING_CONFIG_MISSING',
   'MODEL_PROFILE_BINDING_CONFIG_INVALID',
   'MODEL_PROFILE_BINDING_AUTHORITY_STALE',
   'MODEL_PROFILE_BINDING_DEPLOYMENT_MISSING',
   'MODEL_PROFILE_BINDING_DEPLOYMENT_MISMATCH',
   'MODEL_PROFILE_BINDING_EXPIRED',
   'REFERENCE_MANIFEST_INPUT_INVALID',
   'REFERENCE_MANIFEST_SCOPE_STALE',
   'REFERENCE_MANIFEST_EVIDENCE_INVALID',
   'REFERENCE_MANIFEST_POLICY_INVALID',
   'REFERENCE_MANIFEST_PERSISTENCE_UNCERTAIN',
   'EVIDENCE_INPUT_INVALID',
   'EVIDENCE_SCOPE_NOT_FOUND',
   'EVIDENCE_SCOPE_INVALIDATED',
   'EVIDENCE_SCOPE_EXPIRED',
   'EVIDENCE_AUTHORIZATION_DENIED',
   'EVIDENCE_SOURCE_NOT_FOUND',
   'EVIDENCE_SOURCE_NOT_LIVE',
   'EVIDENCE_OWNER_GENERATION_MISMATCH',
   'EVIDENCE_SCOPE_MISMATCH',
   'EVIDENCE_LOCATOR_NOT_RESOLVABLE',
   'EVIDENCE_PRECISION_UNSUPPORTED',
   'EVIDENCE_OBJECT_NOT_FOUND',
   'EVIDENCE_OBJECT_INTEGRITY',
   'EVIDENCE_RANGE_INVALID',
   'EVIDENCE_HANDLE_NOT_FOUND',
   'EVIDENCE_HANDLE_NOT_LIVE',
   'EVIDENCE_IDENTITY_CONFLICT',
   'EVIDENCE_SETTLEMENT_UNCERTAIN',
   'CITATION_SET_INVALID'
 )
 AND json_extract(NEW.first_failure_json,'$.phase') IN ('PREPARATION','STAGE','RECOVERY')
 AND json_type(NEW.first_failure_json,'$.retryable') IN ('true','false')
 AND (json_extract(NEW.first_failure_json,'$.phase')='PREPARATION' AND json_type(NEW.first_failure_json,'$.stage') IS NULL
   OR json_extract(NEW.first_failure_json,'$.phase') IN ('STAGE','RECOVERY') AND json_extract(NEW.first_failure_json,'$.stage') IN (
   'FREEZE_PROTOCOL_AND_SCOPE',
   'ORIENT',
   'INTERPRET',
   'COMPILE_OBLIGATIONS',
   'PLAN',
   'RETRIEVE_BRANCHES',
   'ACQUIRE_AND_CAPTURE',
   'READ_AND_EXTRACT',
   'ANALYZE_BRANCHES',
   'COUNTER_SEARCH',
   'RECONCILE',
   'FREEZE_EVIDENCE',
   'SYNTHESIZE',
   'VERIFY',
   'AUDIT_CLAIMS',
   'RESOLVE_CITATIONS',
   'CALCULATE_COVERAGE',
   'MATERIALIZE'
 ))
 AND (json_extract(NEW.first_failure_json,'$.retryable')=0 OR
   json_extract(NEW.first_failure_json,'$.phase')='PREPARATION' AND json_extract(NEW.first_failure_json,'$.code')='WORKFLOW_STORAGE_UNAVAILABLE')),0)<>1 THEN RAISE(ABORT,'WORKFLOW_CONFLICT') END);
 SELECT (CASE WHEN EXISTS (SELECT 1 FROM json_each(NEW.first_failure_json) WHERE key NOT IN ('code','phase','stage','retryable'))
   OR (SELECT COUNT(*) FROM json_each(NEW.first_failure_json)) <> (CASE json_extract(NEW.first_failure_json,'$.phase') WHEN 'PREPARATION' THEN 3 ELSE 4 END)
   THEN RAISE(ABORT,'WORKFLOW_CONFLICT') END); SELECT (CASE WHEN json_extract(NEW.first_failure_json,'$.phase') NOT IN ('STAGE','RECOVERY')
   OR json_extract(NEW.first_failure_json,'$.stage') IS NOT json_extract(NEW.request_json,'$.stage')
   THEN RAISE(ABORT,'WORKFLOW_CONFLICT') END);
END;
