import {
  canonicalModelGatewayJson,
  modelGatewaySha256,
  validateModelGatewayTransportPolicy,
  type ModelGatewayTransportPolicyV1,
} from "@eliotr/cloudflare-ai";
import { decodeModelRouteDeployment, type ModelRouteDeployment } from "@eliotr/platform-cloudflare";
import { providerNativeModelProbeInputDigests } from "./provider-native-model-probe-contract.js";

export const PROVIDER_NATIVE_MODEL_CANDIDATE_KIND = "provider-native-v1" as const;
export const PROVIDER_NATIVE_MODEL_PREPARATION_PROTOCOL = "eliotr.provider-native-model-preparation.v1" as const;
export const PROVIDER_NATIVE_MODEL_CANDIDATE_PROTOCOL = "eliotr.provider-native-model-candidate.v1" as const;
export const PROVIDER_NATIVE_KEY_CONFIGURATION_PROTOCOL = "eliotr.research-provider-key-configuration.v1" as const;
export const PROVIDER_NATIVE_MODEL_STAGES = Object.freeze([
  "ANALYZE_BRANCHES", "AUDIT_CLAIMS", "COUNTER_SEARCH", "SYNTHESIZE",
] as const);
export type ProviderNativeModelStage = (typeof PROVIDER_NATIVE_MODEL_STAGES)[number];

const IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9:._/@-]{0,255}$/u;
const SHA256 = /^[a-f0-9]{64}$/u;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const ALIAS = /^eliotr-[a-f0-9]{48}$/u;
const PREPARATION_KEYS = new Set([
  "deployment", "key_binding", "owner_operation_id", "owner_ref", "parameters_sha256", "probe_deployment",
  "probe_parameters_sha256", "probe_prompt_sha256", "probe_schema_sha256", "request_sha256",
  "prepared_at", "preparation_expires_at", "pricing_snapshot_ref", "pricing_snapshot_sha256",
  "project_id", "prompt_sha256", "protocol", "schema_sha256", "stage", "transport_policy",
]);
const PREPARATION_INPUT_KEYS = new Set([
  "deployment", "key_configuration_operation_id", "owner_operation_id", "owner_ref", "parameters_sha256",
  "probe_deployment", "probe_parameters_sha256", "probe_prompt_sha256", "probe_schema_sha256",
  "pricing_snapshot_ref", "pricing_snapshot_sha256", "project_id", "prompt_sha256", "schema_sha256",
  "stage", "transport_policy",
]);
const KEY_BINDING_KEYS = new Set([
  "account_id", "alias", "configuration_metadata_sha256", "gateway_id", "operation_id", "owner_ref",
  "provider_config_id", "provider_id", "project_id", "protocol",
]);
const SELECTION_KEYS = new Set([
  "candidate_kind", "candidate_ref", "candidate_sha256", "qualification_ref",
  "qualification_sha256", "route_ref", "route_version", "stage", "transport_policy",
]);
const CANDIDATE_KEYS = new Set([
  "candidate_kind", "observation_ref", "observation_sha256", "preparation", "preparation_ref",
  "preparation_sha256", "protocol", "qualification_expires_at", "qualification_tier", "verified_at",
]);

export interface ProviderNativeModelKeyBindingV1 {
  readonly protocol: typeof PROVIDER_NATIVE_KEY_CONFIGURATION_PROTOCOL;
  readonly owner_ref: string;
  readonly project_id: string;
  readonly operation_id: string;
  readonly provider_id: "openrouter";
  readonly account_id: string;
  readonly gateway_id: string;
  readonly alias: string;
  readonly provider_config_id: string;
  readonly configuration_metadata_sha256: string;
}

export interface ProviderNativeModelPreparationV1 {
  readonly protocol: typeof PROVIDER_NATIVE_MODEL_PREPARATION_PROTOCOL;
  readonly owner_operation_id: string;
  readonly owner_ref: string;
  readonly project_id: string;
  readonly stage: ProviderNativeModelStage;
  readonly prepared_at: string;
  readonly preparation_expires_at: string;
  readonly deployment: ModelRouteDeployment;
  readonly probe_deployment: ModelRouteDeployment;
  readonly transport_policy: ModelGatewayTransportPolicyV1;
  readonly key_binding: ProviderNativeModelKeyBindingV1;
  readonly pricing_snapshot_ref: string;
  readonly pricing_snapshot_sha256: string;
  readonly prompt_sha256: string;
  readonly schema_sha256: string;
  readonly parameters_sha256: string;
  readonly probe_prompt_sha256: string;
  readonly probe_schema_sha256: string;
  readonly probe_parameters_sha256: string;
  readonly request_sha256: string;
}

/** Server-derived values; key binding and qualification clocks are read/generated by this package. */
export interface ProviderNativeModelPreparationInputV1 {
  readonly owner_operation_id: string;
  readonly owner_ref: string;
  readonly project_id: string;
  readonly stage: ProviderNativeModelStage;
  readonly deployment: ModelRouteDeployment;
  readonly probe_deployment: ModelRouteDeployment;
  readonly transport_policy: ModelGatewayTransportPolicyV1;
  readonly key_configuration_operation_id: string;
  readonly pricing_snapshot_ref: string;
  readonly pricing_snapshot_sha256: string;
  readonly prompt_sha256: string;
  readonly schema_sha256: string;
  readonly parameters_sha256: string;
  readonly probe_prompt_sha256: string;
  readonly probe_schema_sha256: string;
  readonly probe_parameters_sha256: string;
}

export interface ProviderNativeModelCandidateV1 {
  readonly protocol: typeof PROVIDER_NATIVE_MODEL_CANDIDATE_PROTOCOL;
  readonly candidate_kind: typeof PROVIDER_NATIVE_MODEL_CANDIDATE_KIND;
  readonly preparation: ProviderNativeModelPreparationV1;
  readonly preparation_ref: string;
  readonly preparation_sha256: string;
  readonly observation_ref: string;
  readonly observation_sha256: string;
  readonly qualification_tier: "LIVE";
  readonly verified_at: string;
  readonly qualification_expires_at: string;
}

export interface ProviderNativeModelSelectionV1 {
  readonly candidate_kind: typeof PROVIDER_NATIVE_MODEL_CANDIDATE_KIND;
  readonly stage: ProviderNativeModelStage;
  readonly route_ref: string;
  readonly route_version: string;
  readonly candidate_ref: string;
  readonly candidate_sha256: string;
  readonly qualification_ref: string;
  readonly qualification_sha256: string;
  readonly transport_policy: ModelGatewayTransportPolicyV1;
}

export interface StoredProviderNativeModelCandidateV1 {
  readonly candidate_ref: string;
  readonly candidate_sha256: string;
  readonly candidate_json: string;
  readonly candidate: ProviderNativeModelCandidateV1;
}

export interface ProviderNativeModelPreparationReceiptV1 {
  readonly protocol: typeof PROVIDER_NATIVE_MODEL_PREPARATION_PROTOCOL;
  readonly preparation_ref: string;
  readonly preparation_sha256: string;
  readonly owner_operation_id: string;
  readonly stage: ProviderNativeModelStage;
  readonly route_ref: string;
  readonly route_version: string;
  readonly provider: "openrouter";
  readonly exact_model_id: string;
  readonly preparation_expires_at: string;
}

export function providerNativeModelFailure(
  code: "PROVIDER_NATIVE_MODEL_INPUT_INVALID" | "PROVIDER_NATIVE_MODEL_AUTHORITY_STALE" |
    "PROVIDER_NATIVE_MODEL_CONFLICT" | "PROVIDER_NATIVE_MODEL_STORAGE_UNCERTAIN" |
    "PROVIDER_NATIVE_MODEL_QUALIFICATION_UNKNOWN" | "PROVIDER_NATIVE_MODEL_REVOKED",
  message: string,
  cause?: unknown,
): never {
  throw new ProviderNativeModelAuthorityError(code, message, cause);
}

export type ProviderNativeModelErrorCode =
  | "PROVIDER_NATIVE_MODEL_INPUT_INVALID"
  | "PROVIDER_NATIVE_MODEL_AUTHORITY_STALE"
  | "PROVIDER_NATIVE_MODEL_CONFLICT"
  | "PROVIDER_NATIVE_MODEL_STORAGE_UNCERTAIN"
  | "PROVIDER_NATIVE_MODEL_QUALIFICATION_UNKNOWN"
  | "PROVIDER_NATIVE_MODEL_REVOKED";

export class ProviderNativeModelAuthorityError extends Error {
  public readonly code: ProviderNativeModelErrorCode;
  public readonly retryable: boolean;

  public constructor(code: ProviderNativeModelErrorCode, message: string, cause?: unknown) {
    super(message, cause === undefined ? undefined : { cause });
    this.name = "ProviderNativeModelAuthorityError";
    this.code = code;
    this.retryable = code === "PROVIDER_NATIVE_MODEL_STORAGE_UNCERTAIN";
  }
}

function record(value: unknown, keys: ReadonlySet<string>, label: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value) ||
      (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null)) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", `${label} must be a plain object`);
  }
  const result = value as Record<string, unknown>;
  if (Object.keys(result).some((key) => !keys.has(key))) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", `${label} contains an unsupported property`);
  }
  return result;
}

function identifier(value: unknown, label: string): string {
  if (typeof value !== "string" || !IDENTIFIER.test(value)) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", `${label} is invalid`);
  }
  return value;
}

function digest(value: unknown, label: string): string {
  if (typeof value !== "string" || !SHA256.test(value)) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", `${label} is invalid`);
  }
  return value;
}

function stage(value: unknown): ProviderNativeModelStage {
  if (typeof value !== "string" || !(PROVIDER_NATIVE_MODEL_STAGES as readonly string[]).includes(value)) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model stage is invalid");
  }
  return value as ProviderNativeModelStage;
}

function canonicalTime(value: unknown, label: string): string {
  if (typeof value !== "string" || !Number.isFinite(Date.parse(value)) ||
      new Date(Date.parse(value)).toISOString() !== value) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", `${label} is not canonical UTC time`);
  }
  return value;
}

export function decodeProviderNativeModelKeyBinding(raw: unknown): ProviderNativeModelKeyBindingV1 {
  const value = record(raw, KEY_BINDING_KEYS, "provider key binding");
  const accountId = value.account_id;
  const operationId = value.operation_id;
  const alias = value.alias;
  if (value.protocol !== PROVIDER_NATIVE_KEY_CONFIGURATION_PROTOCOL || value.provider_id !== "openrouter" ||
      typeof accountId !== "string" || !/^[A-Fa-f0-9]{32}$/u.test(accountId) ||
      typeof operationId !== "string" || !UUID.test(operationId) ||
      typeof alias !== "string" || !ALIAS.test(alias)) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "configured OpenRouter key binding is invalid");
  }
  const ownerRef = identifier(value.owner_ref, "provider key owner");
  const projectId = identifier(value.project_id, "provider key project");
  return Object.freeze({ protocol: PROVIDER_NATIVE_KEY_CONFIGURATION_PROTOCOL,
    owner_ref: ownerRef,
    project_id: projectId, operation_id: operationId, provider_id: "openrouter",
    account_id: accountId.toLowerCase(), gateway_id: identifier(value.gateway_id, "provider key gateway"),
    alias, provider_config_id: identifier(value.provider_config_id, "provider config ID"),
    configuration_metadata_sha256: digest(value.configuration_metadata_sha256, "provider key metadata digest") });
}

export function decodeProviderNativeModelPreparation(raw: unknown): ProviderNativeModelPreparationV1 {
  const value = record(raw, PREPARATION_KEYS, "native model preparation");
  let deployment: ModelRouteDeployment;
  let probeDeployment: ModelRouteDeployment;
  let transportPolicy: ModelGatewayTransportPolicyV1;
  try {
    deployment = decodeModelRouteDeployment(value.deployment);
    probeDeployment = decodeModelRouteDeployment(value.probe_deployment);
    transportPolicy = validateModelGatewayTransportPolicy(value.transport_policy);
  } catch (cause) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model deployment or transport policy is invalid", cause);
  }
  const keyBinding = decodeProviderNativeModelKeyBinding(value.key_binding);
  const ownerOperationId = value.owner_operation_id;
  const ownerRef = identifier(value.owner_ref, "native model owner");
  const projectId = identifier(value.project_id, "native model project");
  const preparedAt = canonicalTime(value.prepared_at, "native model preparation time");
  const preparationExpiresAt = canonicalTime(value.preparation_expires_at, "native model preparation expiry");
  if (value.protocol !== PROVIDER_NATIVE_MODEL_PREPARATION_PROTOCOL ||
      transportPolicy.api !== "openrouter-chat-completions" || transportPolicy.provider !== "openrouter" ||
      transportPolicy.billing.mode !== "byok" || transportPolicy.billing.free_only !== true ||
      transportPolicy.billing.alias !== keyBinding.alias ||
      keyBinding.owner_ref !== ownerRef || keyBinding.project_id !== projectId || deployment.pricing_snapshot_ref !== value.pricing_snapshot_ref ||
      probeDeployment.route_ref !== deployment.route_ref || probeDeployment.route_version !== deployment.route_version ||
      probeDeployment.pricing_snapshot_ref !== deployment.pricing_snapshot_ref ||
      typeof ownerOperationId !== "string" || !UUID.test(ownerOperationId) ||
      Date.parse(preparationExpiresAt) <= Date.parse(preparedAt)) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model preparation identity is inconsistent");
  }
  const parametersSha = digest(value.parameters_sha256, "request parameters digest");
  const probeParametersSha = digest(value.probe_parameters_sha256, "probe request parameters digest");
  if (parametersSha !== deployment.parameters_digest) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native request parameters do not match the deployment");
  }
  if (probeParametersSha !== probeDeployment.parameters_digest) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native probe parameters do not match the probe deployment");
  }
  return Object.freeze({
    protocol: PROVIDER_NATIVE_MODEL_PREPARATION_PROTOCOL,
    owner_operation_id: ownerOperationId,
    owner_ref: ownerRef,
    project_id: projectId,
    stage: stage(value.stage),
    prepared_at: preparedAt,
    preparation_expires_at: preparationExpiresAt,
    deployment,
    probe_deployment: probeDeployment,
    transport_policy: transportPolicy,
    key_binding: keyBinding,
    pricing_snapshot_ref: identifier(value.pricing_snapshot_ref, "pricing snapshot reference"),
    pricing_snapshot_sha256: digest(value.pricing_snapshot_sha256, "pricing snapshot digest"),
    prompt_sha256: digest(value.prompt_sha256, "prompt digest"),
    schema_sha256: digest(value.schema_sha256, "schema digest"),
    parameters_sha256: parametersSha,
    probe_prompt_sha256: digest(value.probe_prompt_sha256, "native probe prompt digest"),
    probe_schema_sha256: digest(value.probe_schema_sha256, "native probe schema digest"),
    probe_parameters_sha256: probeParametersSha,
    request_sha256: digest(value.request_sha256, "native preparation request digest"),
  });
}

export function decodeProviderNativeModelPreparationInput(raw: unknown): ProviderNativeModelPreparationInputV1 {
  const value = record(raw, PREPARATION_INPUT_KEYS, "native model preparation input");
  let deployment: ModelRouteDeployment;
  let probeDeployment: ModelRouteDeployment;
  let transportPolicy: ModelGatewayTransportPolicyV1;
  try {
    deployment = decodeModelRouteDeployment(value.deployment);
    probeDeployment = decodeModelRouteDeployment(value.probe_deployment);
    transportPolicy = validateModelGatewayTransportPolicy(value.transport_policy);
  } catch (cause) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model deployment or transport policy is invalid", cause);
  }
  const operationId = value.owner_operation_id;
  const keyOperationId = value.key_configuration_operation_id;
  const projectId = identifier(value.project_id, "native model project");
  if (typeof operationId !== "string" || !UUID.test(operationId) ||
      typeof keyOperationId !== "string" || !UUID.test(keyOperationId) ||
      transportPolicy.api !== "openrouter-chat-completions" || transportPolicy.provider !== "openrouter" ||
      transportPolicy.billing.mode !== "byok" || transportPolicy.billing.free_only !== true ||
      deployment.pricing_snapshot_ref !== value.pricing_snapshot_ref ||
      probeDeployment.route_ref !== deployment.route_ref || probeDeployment.route_version !== deployment.route_version ||
      probeDeployment.pricing_snapshot_ref !== deployment.pricing_snapshot_ref) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native preparation input identity is inconsistent");
  }
  const parametersSha = digest(value.parameters_sha256, "request parameters digest");
  const probeParametersSha = digest(value.probe_parameters_sha256, "probe request parameters digest");
  if (parametersSha !== deployment.parameters_digest) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native request parameters do not match the deployment");
  }
  if (probeParametersSha !== probeDeployment.parameters_digest) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native probe parameters do not match the probe deployment");
  }
  return Object.freeze({
    owner_operation_id: operationId,
    owner_ref: identifier(value.owner_ref, "native model owner"),
    project_id: projectId,
    stage: stage(value.stage),
    deployment,
    probe_deployment: probeDeployment,
    transport_policy: transportPolicy,
    key_configuration_operation_id: keyOperationId,
    pricing_snapshot_ref: identifier(value.pricing_snapshot_ref, "pricing snapshot reference"),
    pricing_snapshot_sha256: digest(value.pricing_snapshot_sha256, "pricing snapshot digest"),
    prompt_sha256: digest(value.prompt_sha256, "prompt digest"),
    schema_sha256: digest(value.schema_sha256, "schema digest"),
    parameters_sha256: parametersSha,
    probe_prompt_sha256: digest(value.probe_prompt_sha256, "native probe prompt digest"),
    probe_schema_sha256: digest(value.probe_schema_sha256, "native probe schema digest"),
    probe_parameters_sha256: probeParametersSha,
  });
}

export async function assertProviderNativeModelProbeBinding(
  preparation: ProviderNativeModelPreparationV1 | ProviderNativeModelPreparationInputV1,
): Promise<void> {
  const digests = await providerNativeModelProbeInputDigests();
  if (preparation.probe_prompt_sha256 !== digests.probe_prompt_sha256 ||
      preparation.probe_schema_sha256 !== digests.probe_schema_sha256 ||
      preparation.probe_deployment.route_ref !== preparation.deployment.route_ref ||
      preparation.probe_deployment.route_version !== preparation.deployment.route_version ||
      preparation.probe_deployment.pricing_snapshot_ref !== preparation.deployment.pricing_snapshot_ref ||
      preparation.probe_parameters_sha256 !== preparation.probe_deployment.parameters_digest) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_AUTHORITY_STALE", "stored native connectivity probe binding differs from its fixed contract");
  }
}

export function decodeProviderNativeModelCandidate(raw: unknown): ProviderNativeModelCandidateV1 {
  const value = record(raw, CANDIDATE_KEYS, "native model candidate");
  const preparation = decodeProviderNativeModelPreparation(value.preparation);
  if (value.protocol !== PROVIDER_NATIVE_MODEL_CANDIDATE_PROTOCOL ||
      value.candidate_kind !== PROVIDER_NATIVE_MODEL_CANDIDATE_KIND || value.qualification_tier !== "LIVE") {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model candidate kind or qualification tier is invalid");
  }
  const verifiedAt = canonicalTime(value.verified_at, "native model verification time");
  const expiresAt = canonicalTime(value.qualification_expires_at, "native model qualification expiry");
  if (Date.parse(expiresAt) <= Date.parse(verifiedAt)) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model qualification expiry is invalid");
  }
  return Object.freeze({
    protocol: PROVIDER_NATIVE_MODEL_CANDIDATE_PROTOCOL,
    candidate_kind: PROVIDER_NATIVE_MODEL_CANDIDATE_KIND,
    preparation,
    preparation_ref: identifier(value.preparation_ref, "preparation reference"),
    preparation_sha256: digest(value.preparation_sha256, "preparation digest"),
    observation_ref: identifier(value.observation_ref, "observation reference"),
    observation_sha256: digest(value.observation_sha256, "observation digest"),
    qualification_tier: "LIVE",
    verified_at: verifiedAt,
    qualification_expires_at: expiresAt,
  });
}

export function decodeProviderNativeModelSelection(raw: unknown): ProviderNativeModelSelectionV1 {
  const value = record(raw, SELECTION_KEYS, "native model selection");
  let transportPolicy: ModelGatewayTransportPolicyV1;
  try { transportPolicy = validateModelGatewayTransportPolicy(value.transport_policy); }
  catch (cause) { providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native selection transport policy is invalid", cause); }
  if (value.candidate_kind !== PROVIDER_NATIVE_MODEL_CANDIDATE_KIND ||
      transportPolicy.api !== "openrouter-chat-completions" || transportPolicy.provider !== "openrouter" ||
      transportPolicy.billing.mode !== "byok" || transportPolicy.billing.free_only !== true) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model selection kind or provider is invalid");
  }
  return Object.freeze({ candidate_kind: PROVIDER_NATIVE_MODEL_CANDIDATE_KIND, stage: stage(value.stage),
    route_ref: identifier(value.route_ref, "selection route"), route_version: identifier(value.route_version, "selection route version"),
    candidate_ref: identifier(value.candidate_ref, "candidate reference"), candidate_sha256: digest(value.candidate_sha256, "candidate digest"),
    qualification_ref: identifier(value.qualification_ref, "qualification reference"), qualification_sha256: digest(value.qualification_sha256, "qualification digest"),
    transport_policy: transportPolicy });
}

export async function createProviderNativeModelPreparation(input: Readonly<{
  readonly input: ProviderNativeModelPreparationInputV1;
  readonly key_binding: ProviderNativeModelKeyBindingV1;
  readonly prepared_at: string;
  readonly preparation_expires_at: string;
}>): Promise<Readonly<{
  readonly preparation: ProviderNativeModelPreparationV1;
  readonly preparation_ref: string;
  readonly preparation_sha256: string;
  readonly preparation_json: string;
  readonly request_sha256: string;
  readonly receipt: ProviderNativeModelPreparationReceiptV1;
}>> {
  const value = decodeProviderNativeModelPreparationInput(input.input);
  const keyBinding = decodeProviderNativeModelKeyBinding(input.key_binding);
  if (keyBinding.operation_id !== value.key_configuration_operation_id ||
      keyBinding.owner_ref !== value.owner_ref ||
      keyBinding.project_id !== value.project_id ||
      value.transport_policy.billing.mode !== "byok" ||
      keyBinding.alias !== value.transport_policy.billing.alias) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_AUTHORITY_STALE", "native provider key and server-selected policy do not match");
  }
  const probeDigests = await providerNativeModelProbeInputDigests();
  if (value.probe_prompt_sha256 !== probeDigests.probe_prompt_sha256 ||
      value.probe_schema_sha256 !== probeDigests.probe_schema_sha256) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native probe prompt or schema differs from the fixed connectivity contract");
  }
  const requestMaterial = Object.freeze({
    input: value,
    key_binding: keyBinding,
  });
  const requestSha = await modelGatewaySha256(canonicalModelGatewayJson(requestMaterial));
  const preparation = decodeProviderNativeModelPreparation({
    protocol: PROVIDER_NATIVE_MODEL_PREPARATION_PROTOCOL,
    owner_operation_id: value.owner_operation_id,
    owner_ref: value.owner_ref,
    project_id: value.project_id,
    stage: value.stage,
    prepared_at: input.prepared_at,
    preparation_expires_at: input.preparation_expires_at,
    deployment: value.deployment,
    probe_deployment: value.probe_deployment,
    transport_policy: value.transport_policy,
    key_binding: keyBinding,
    pricing_snapshot_ref: value.pricing_snapshot_ref,
    pricing_snapshot_sha256: value.pricing_snapshot_sha256,
    prompt_sha256: value.prompt_sha256,
    schema_sha256: value.schema_sha256,
    parameters_sha256: value.parameters_sha256,
    probe_prompt_sha256: value.probe_prompt_sha256,
    probe_schema_sha256: value.probe_schema_sha256,
    probe_parameters_sha256: value.probe_parameters_sha256,
    request_sha256: requestSha,
  });
  const material = await providerNativeModelJson(preparation);
  const preparationRef = `provider-native-model-preparation-${material.sha256}`;
  const receipt: ProviderNativeModelPreparationReceiptV1 = Object.freeze({
    protocol: PROVIDER_NATIVE_MODEL_PREPARATION_PROTOCOL,
    preparation_ref: preparationRef,
    preparation_sha256: material.sha256,
    owner_operation_id: preparation.owner_operation_id,
    stage: preparation.stage,
    route_ref: preparation.deployment.route_ref,
    route_version: preparation.deployment.route_version,
    provider: "openrouter",
    exact_model_id: preparation.transport_policy.model,
    preparation_expires_at: preparation.preparation_expires_at,
  });
  return Object.freeze({
    preparation,
    preparation_ref: preparationRef,
    preparation_sha256: material.sha256,
    preparation_json: material.json,
    request_sha256: requestSha,
    receipt,
  });
}

export async function providerNativeModelJson(value: unknown): Promise<Readonly<{ json: string; sha256: string }>> {
  const json = canonicalModelGatewayJson(value);
  if (new TextEncoder().encode(json).byteLength > 65536) {
    providerNativeModelFailure("PROVIDER_NATIVE_MODEL_INPUT_INVALID", "native model authority document exceeds its bound");
  }
  return Object.freeze({ json, sha256: await modelGatewaySha256(json) });
}
